\set ON_ERROR_STOP on

do $roles$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then
    create role anon nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then
    create role authenticated nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'service_role') then
    create role service_role nologin bypassrls;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'mila_acesso_restrito') then
    create role mila_acesso_restrito nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'sol_acesso_restrito') then
    create role sol_acesso_restrito nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'fabio_agent') then
    create role fabio_agent nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'lia_acesso_restrito') then
    create role lia_acesso_restrito nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'maria_lareport_rpc') then
    create role maria_lareport_rpc nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'ml_jobs') then
    create role ml_jobs nologin;
  end if;
end;
$roles$;

create schema cron;

create table cron.job (
  jobid bigint generated by default as identity primary key,
  jobname text not null,
  schedule text not null,
  command text not null
);

create function cron.schedule(
  p_jobname text,
  p_schedule text,
  p_command text
)
returns bigint
language plpgsql
as $function$
declare
  v_jobid bigint;
begin
  insert into cron.job (jobname, schedule, command)
  values (p_jobname, p_schedule, p_command)
  returning jobid into v_jobid;
  return v_jobid;
end;
$function$;

create function cron.unschedule(p_jobid bigint)
returns boolean
language plpgsql
as $function$
begin
  delete from cron.job where jobid = p_jobid;
  return found;
end;
$function$;

create table public.whatsapp_caixas (
  id integer primary key,
  ativo boolean not null default true
);

insert into public.whatsapp_caixas (id, ativo)
values (1, true), (2, false);

create table public.webhook_debug_log (
  id bigint generated by default as identity primary key,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.webhook_debug_log enable row level security;
grant all on table public.webhook_debug_log
  to anon, authenticated, service_role, mila_acesso_restrito,
     sol_acesso_restrito, fabio_agent, lia_acesso_restrito,
     maria_lareport_rpc, ml_jobs;

insert into public.webhook_debug_log (payload, created_at)
values
  ('{"fixture": 1}'::jsonb, now() - interval '20 days'),
  ('{"fixture": 2}'::jsonb, now() - interval '10 days'),
  ('{"fixture": 3}'::jsonb, now());

\ir ../../supabase/migrations/20260801220000_webhook_inbound_secrets_debug_retention.sql

do $assert_expurge_and_acl$
begin
  if (select count(*) from public.webhook_debug_log) <> 0 then
    raise exception 'linhas legadas nao foram expurgadas';
  end if;

  if has_table_privilege('service_role', 'public.webhook_debug_log', 'insert') then
    raise exception 'service_role ainda escreve no debug legado';
  end if;

  if has_table_privilege('authenticated', 'public.whatsapp_caixa_webhook_secrets', 'select')
     or has_table_privilege('authenticated', 'public.webhook_diagnosticos_sanitizados', 'select') then
    raise exception 'authenticated leu tabela backend-only';
  end if;
end;
$assert_expurge_and_acl$;

insert into public.whatsapp_caixa_webhook_secrets (
  caixa_id,
  secret_hash_sha256
)
values
  (1, repeat('a', 64)),
  (2, repeat('b', 64));

do $assert_validator$
begin
  if not public.validar_webhook_caixa_hash(1, repeat('a', 64)) then
    raise exception 'hash correto da caixa ativa foi rejeitado';
  end if;
  if public.validar_webhook_caixa_hash(2, repeat('b', 64)) then
    raise exception 'caixa inativa foi aceita';
  end if;
  if public.validar_webhook_caixa_hash(1, repeat('b', 64))
     or public.validar_webhook_caixa_hash(null, null)
     or public.validar_webhook_caixa_hash(1, 'invalido') then
    raise exception 'hash invalido foi aceito';
  end if;
end;
$assert_validator$;

set role service_role;
insert into public.webhook_diagnosticos_sanitizados (
  correlation_id,
  caixa_id,
  event_type,
  route,
  result,
  occurred_at
)
values
  ('11111111-1111-4111-8111-111111111111', 1, 'messages', 'evasao', 'accepted', now() - interval '8 days'),
  ('22222222-2222-4222-8222-222222222222', 1, 'messages', 'evasao', 'accepted', now());

do $assert_authenticated_denied$
begin
  if public.expurgar_webhook_diagnosticos_sanitizados() <> 1 then
    raise exception 'retencao de sete dias divergiu';
  end if;
end;
$assert_authenticated_denied$;
reset role;

do $assert_retention$
begin
  if (select count(*) from public.webhook_diagnosticos_sanitizados) <> 1 then
    raise exception 'retencao de sete dias divergiu';
  end if;
end;
$assert_retention$;

create function public.fixture_webhook_debug_writer()
returns void
language sql
as $function$
  insert into public.webhook_debug_log (payload)
  values ('{}'::jsonb);
$function$;

do $assert_writer_guard$
declare
  v_writer text;
begin
  select p.proname
    into v_writer
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public'
    and p.prokind in ('f', 'p')
    and pg_get_functiondef(p.oid) ~* (
      '(insert[[:space:]]+into|update|delete[[:space:]]+from|'
      || 'truncate([[:space:]]+table)?)[[:space:]]+'
      || '(public[.])?webhook_debug_log'
    )
  limit 1;

  if v_writer is null then
    raise exception 'writer guard nao bloqueou escritor persistente';
  end if;
end;
$assert_writer_guard$;

drop function public.fixture_webhook_debug_writer();

\ir ../../scripts/verify-webhook-inbound-security.sql

select 'WEBHOOK_INBOUND_SECURITY_PG17_OK' as resultado;

create database webhook_inbound_empty_fixture;
\connect webhook_inbound_empty_fixture

create schema cron;

create table cron.job (
  jobid bigint generated by default as identity primary key,
  jobname text not null,
  schedule text not null,
  command text not null
);

create function cron.schedule(
  p_jobname text,
  p_schedule text,
  p_command text
)
returns bigint
language plpgsql
as $function$
declare
  v_jobid bigint;
begin
  insert into cron.job (jobname, schedule, command)
  values (p_jobname, p_schedule, p_command)
  returning jobid into v_jobid;
  return v_jobid;
end;
$function$;

create function cron.unschedule(p_jobid bigint)
returns boolean
language plpgsql
as $function$
begin
  delete from cron.job where jobid = p_jobid;
  return found;
end;
$function$;

create table public.whatsapp_caixas (
  id integer primary key,
  ativo boolean not null default true
);

create table public.webhook_debug_log (
  id bigint generated by default as identity primary key,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.webhook_debug_log enable row level security;

\ir ../../supabase/migrations/20260801220000_webhook_inbound_secrets_debug_retention.sql

do $assert_empty$
begin
  if (select count(*) from public.webhook_debug_log) <> 0 then
    raise exception 'banco vazio ganhou linha durante o expurgo';
  end if;
end;
$assert_empty$;

select 'WEBHOOK_INBOUND_EMPTY_PG17_OK' as resultado;

\connect postgres
drop database webhook_inbound_empty_fixture;
