\set ON_ERROR_STOP on

drop schema if exists public cascade;
drop schema if exists auth cascade;
create schema public;
create schema auth;
grant usage on schema public, auth to public;

do $roles$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then
    create role anon nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then
    create role authenticated nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'service_role') then
    create role service_role nologin bypassrls;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'mila_acesso_restrito') then
    create role mila_acesso_restrito nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'sol_acesso_restrito') then
    create role sol_acesso_restrito nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'fabio_agent') then
    create role fabio_agent nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'lia_acesso_restrito') then
    create role lia_acesso_restrito nologin;
  end if;
end;
$roles$;

create or replace function auth.uid()
returns uuid
language sql
stable
as $function$
  select nullif(
    current_setting('request.jwt.claim.sub', true),
    ''
  )::uuid;
$function$;

create table public.unidades (
  id uuid primary key,
  nome text not null
);

create table public.usuarios (
  id integer primary key,
  auth_user_id uuid unique,
  nome text not null,
  perfil text not null,
  unidade_id uuid references public.unidades(id),
  ativo boolean not null default true
);

create table public.whatsapp_caixas (
  id integer generated by default as identity primary key,
  nome varchar not null,
  numero varchar,
  uazapi_url varchar not null,
  uazapi_token varchar not null,
  unidade_id uuid references public.unidades(id),
  ativo boolean default true,
  webhook_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  funcao text not null default 'agente'
    check (funcao in ('agente', 'sistema', 'ambos', 'administrativo')),
  provedor text not null default 'uazapi',
  waha_url text,
  waha_session text,
  waha_api_key text,
  departamento text not null default 'administrativo'
    check (departamento in ('administrativo', 'sucesso_aluno'))
);

alter table public.whatsapp_caixas enable row level security;
create policy whatsapp_caixas_select
  on public.whatsapp_caixas for select to authenticated using (true);
create policy whatsapp_caixas_insert
  on public.whatsapp_caixas for insert to authenticated with check (true);
create policy whatsapp_caixas_update
  on public.whatsapp_caixas for update to authenticated
  using (true) with check (true);
create policy whatsapp_caixas_delete
  on public.whatsapp_caixas for delete to authenticated using (true);

grant all on table public.whatsapp_caixas
  to anon, authenticated, service_role, mila_acesso_restrito,
     sol_acesso_restrito, fabio_agent, lia_acesso_restrito;
grant all on sequence public.whatsapp_caixas_id_seq
  to anon, authenticated, service_role, mila_acesso_restrito,
     sol_acesso_restrito, fabio_agent, lia_acesso_restrito;

insert into public.unidades (id, nome)
values
  ('10000000-0000-4000-8000-000000000001', 'Unidade A'),
  ('20000000-0000-4000-8000-000000000002', 'Unidade B');

insert into public.usuarios (
  id,
  auth_user_id,
  nome,
  perfil,
  unidade_id
)
values
  (
    1,
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
    'Admin Teste',
    'admin',
    null
  ),
  (
    2,
    'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
    'Unidade Teste',
    'unidade',
    '10000000-0000-4000-8000-000000000001'
  );

insert into public.whatsapp_caixas (
  id,
  nome,
  numero,
  uazapi_url,
  uazapi_token,
  unidade_id,
  ativo,
  funcao,
  provedor,
  waha_url,
  waha_session,
  waha_api_key,
  departamento
)
values
  (
    1,
    'Caixa A',
    '5521999991111',
    'https://uazapi-a.example',
    'segredo-uazapi-a',
    '10000000-0000-4000-8000-000000000001',
    true,
    'administrativo',
    'uazapi',
    null,
    null,
    null,
    'administrativo'
  ),
  (
    2,
    'Caixa B',
    '5521999992222',
    'https://uazapi-b.example',
    'segredo-uazapi-b',
    '20000000-0000-4000-8000-000000000002',
    true,
    'administrativo',
    'waha',
    'https://waha-b.example',
    'sessao-b',
    'segredo-waha-b',
    'sucesso_aluno'
  ),
  (
    3,
    'Caixa Global',
    '5521999993333',
    'https://uazapi-global.example',
    'segredo-uazapi-global',
    null,
    true,
    'sistema',
    'uazapi',
    null,
    null,
    null,
    'administrativo'
  );

select setval(
  'public.whatsapp_caixas_id_seq',
  (select max(id) from public.whatsapp_caixas)
);

\ir ../../supabase/migrations/20260730180100_whatsapp_caixas_credenciais_privadas.sql

do $assert_privileges$
begin
  if has_table_privilege(
    'authenticated',
    'public.whatsapp_caixas',
    'select'
  ) then
    raise exception 'authenticated ainda possui SELECT bruto';
  end if;

  if has_table_privilege(
    'sol_acesso_restrito',
    'public.whatsapp_caixas',
    'select'
  ) then
    raise exception 'Sol ainda possui SELECT bruto';
  end if;

  if not has_table_privilege(
    'service_role',
    'public.whatsapp_caixas',
    'select'
  ) then
    raise exception 'service_role perdeu SELECT necessário';
  end if;

  if has_function_privilege(
    'anon',
    'public.listar_whatsapp_caixas_seguras(uuid,boolean)',
    'execute'
  ) then
    raise exception 'anon executa listagem segura';
  end if;
end;
$assert_privileges$;

set role authenticated;
select set_config(
  'request.jwt.claim.sub',
  'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
  false
);

do $assert_direct_denied$
begin
  begin
    perform uazapi_token, waha_api_key
    from public.whatsapp_caixas;
    raise exception 'authenticated leu token UAZAPI ou chave WAHA bruta';
  exception
    when insufficient_privilege then null;
  end;
end;
$assert_direct_denied$;

do $assert_unit_scope$
declare
  v_count integer;
  v_numero text;
begin
  select count(*), min(numero_mascarado)
    into v_count, v_numero
  from public.listar_whatsapp_caixas_seguras(null, false);

  if v_count <> 1 then
    raise exception 'usuário de unidade recebeu % caixas, esperado 1', v_count;
  end if;
  if v_numero = '5521999991111' or v_numero not like '••••%' then
    raise exception 'telefone operacional não foi mascarado';
  end if;

  begin
    perform *
    from public.listar_whatsapp_caixas_seguras(
      '20000000-0000-4000-8000-000000000002',
      false
    );
    raise exception 'usuário ampliou escopo para outra unidade';
  exception
    when insufficient_privilege then null;
  end;
end;
$assert_unit_scope$;

select set_config(
  'request.jwt.claim.sub',
  'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
  false
);

do $assert_admin_projection$
declare
  v_count integer;
  v_payload jsonb;
begin
  select count(*) into v_count
  from public.listar_whatsapp_caixas_administracao();
  if v_count <> 3 then
    raise exception 'admin recebeu % caixas, esperado 3', v_count;
  end if;

  select to_jsonb(caixa) into v_payload
  from public.listar_whatsapp_caixas_administracao() caixa
  where caixa.id = 1;

  if v_payload ? 'uazapi_token' or v_payload ? 'waha_api_key' then
    raise exception 'projeção administrativa retornou segredo';
  end if;
  if not (v_payload ->> 'uazapi_token_configurado')::boolean then
    raise exception 'flag de credencial configurada ausente';
  end if;
end;
$assert_admin_projection$;

select public.salvar_whatsapp_caixa_admin(
  1,
  'Caixa A atualizada',
  '5521999991111',
  'https://uazapi-a.example',
  null,
  '10000000-0000-4000-8000-000000000001',
  null,
  true,
  'administrativo',
  'administrativo',
  'uazapi',
  null,
  null,
  null
);

reset role;

do $assert_preserved$
begin
  if (
    select uazapi_token <> 'segredo-uazapi-a'
    from public.whatsapp_caixas
    where id = 1
  ) then
    raise exception 'token omitido não foi preservado';
  end if;
end;
$assert_preserved$;

set role authenticated;
select set_config(
  'request.jwt.claim.sub',
  'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
  false
);

select public.salvar_whatsapp_caixa_admin(
  1,
  'Caixa A atualizada',
  '5521999991111',
  'https://uazapi-a.example',
  'segredo-uazapi-a-rotacionado',
  '10000000-0000-4000-8000-000000000001',
  null,
  true,
  'administrativo',
  'administrativo',
  'uazapi',
  null,
  null,
  null
);

reset role;

do $assert_rotation$
begin
  if (
    select uazapi_token <> 'segredo-uazapi-a-rotacionado'
    from public.whatsapp_caixas
    where id = 1
  ) then
    raise exception 'rotação write-only não persistiu';
  end if;

  if (
    select count(*)
    from public.whatsapp_caixas_credenciais_auditoria
    where caixa_id = 1
      and credencial = 'uazapi_token'
      and auth_user_id = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'
  ) <> 1 then
    raise exception 'rotação não gerou auditoria sem segredo';
  end if;
end;
$assert_rotation$;

\ir ../../supabase/migrations/20260730180100_whatsapp_caixas_credenciais_privadas.sql

set role service_role;
select count(*) from public.whatsapp_caixas;
reset role;

select 'WHATSAPP_CAIXAS_CREDENCIAIS_PRIVADAS_PG17_OK' as resultado;
