do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then create role anon nologin; end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then create role authenticated nologin; end if;
  if not exists (select 1 from pg_roles where rolname = 'service_role') then create role service_role nologin bypassrls; end if;
  if not exists (select 1 from pg_roles where rolname = 'sol_acesso_restrito') then create role sol_acesso_restrito nologin; end if;
end $$;

create schema if not exists auth;
create or replace function auth.uid() returns uuid language sql stable as $$ select null::uuid $$;

create extension if not exists pg_cron;
create extension if not exists pg_net;

create table public.unidades (
  id uuid primary key default gen_random_uuid(),
  nome text not null
);

create table public.usuarios (
  id integer generated by default as identity primary key,
  auth_user_id uuid,
  ativo boolean default true,
  perfil text
);

create table public.professores (
  id integer generated by default as identity primary key,
  nome text not null,
  usuario_id integer references public.usuarios(id),
  ativo boolean default true
);

create table public.alunos (
  id integer generated by default as identity primary key,
  nome text not null
);

create table public.aulas_emusys (
  id integer generated by default as identity primary key,
  emusys_id integer not null,
  unidade_id uuid not null references public.unidades(id),
  data_aula date not null,
  data_hora_inicio timestamptz not null,
  data_hora_fim timestamptz,
  duracao_minutos integer,
  tipo text,
  categoria text,
  turma_nome text,
  curso_nome text,
  sala_nome text,
  professor_id integer references public.professores(id),
  cancelada boolean default false,
  anotacoes_fabio text
);

create table public.aluno_presenca (
  id uuid primary key default gen_random_uuid(),
  aluno_id integer not null references public.alunos(id),
  professor_id integer references public.professores(id),
  unidade_id uuid not null references public.unidades(id),
  data_aula date not null,
  horario_aula time,
  status varchar(20) check (status in ('presente', 'ausente', 'remarcou', 'pendente')),
  respondido_por varchar(30) check (respondido_por in ('professor_whatsapp', 'manual', 'sistema', 'emusys')),
  respondido_em timestamptz,
  created_at timestamptz default now(),
  aula_emusys_id integer references public.aulas_emusys(id),
  curso_nome varchar(100),
  turma_nome varchar(100),
  sala_nome varchar(100),
  constraint uq_presenca_aluno_aula unique (aluno_id, aula_emusys_id)
);

alter table public.aluno_presenca enable row level security;
create policy "Authenticated users can manage attendance" on public.aluno_presenca for all using (true);
create policy "Public can update attendance via token" on public.aluno_presenca for update using (true);
create policy lume_readonly_select on public.aluno_presenca for select to sol_acesso_restrito using (true);

create table public.professores_unidades (
  id integer generated by default as identity primary key,
  professor_id integer not null references public.professores(id),
  unidade_id uuid not null references public.unidades(id),
  disponibilidade jsonb,
  emusys_id integer,
  validacao_status text,
  last_seen_em timestamptz,
  payload_emusys jsonb default '{}'::jsonb,
  match_score numeric(5,2),
  origem text,
  updated_at timestamptz default now()
);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create or replace function public.is_admin()
returns boolean language sql stable as $$ select false $$;

create or replace function public.get_user_unidade_id()
returns uuid language sql stable as $$ select null::uuid $$;

create or replace function public.usuario_tem_permissao(
  p_usuario_id integer,
  p_codigo_permissao varchar,
  p_unidade_id uuid default null
)
returns boolean language sql stable as $$ select false $$;

select vault.create_secret('test-token', 'sync_presenca_edge_token');
