export { EventosPage } from './EventosPage';
export { EventoDetalhePage } from './EventoDetalhePage';
export { AlunosTab } from './AlunosTab';
export { GradeTab } from './GradeTab';
export { SeletorApresentacao } from './SeletorApresentacao';
export { PalcoTab } from './PalcoTab';
export { PalcoApresentacao } from './PalcoApresentacao';
export { AvisoEmDesenvolvimento } from './AvisoEmDesenvolvimento';
export { default } from './EventosPage';
