-- =============================================================================
-- ROLLBACK / BASELINE DE GRANTS — Auditoria de Segurança C1 (revogação anon)
-- Gerado em 2026-06-30, ANTES de avançar os sprints de revogação.
-- Uso: se algum sprint quebrar algo, rode o bloco correspondente para restaurar
-- o EXECUTE como estava. NÃO é uma migration (não fica em supabase/migrations/);
-- é um snapshot de segurança para reversão manual.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- SPRINT 1 (trigger functions) — ROLLBACK
-- Estado ORIGINAL (antes da migration 20260630130000): todas tinham EXECUTE para
-- PUBLIC, anon, authenticated, postgres, service_role. postgres/service_role
-- permaneceram; este bloco restaura PUBLIC/anon/authenticated.
-- (Obs: o esperado é NUNCA precisar disto — triggers não dependem de EXECUTE.)
-- -----------------------------------------------------------------------------
GRANT EXECUTE ON FUNCTION public.set_updated_at_caixa()                           TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.fn_audit_log()                                   TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.fn_bi_conversation_autofill()                    TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.fn_log_ocorrencia_criada()                       TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.preencher_campos_retencao_movimentacoes_admin()  TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.enqueue_sync_student_studio()                    TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.sync_evasao_to_dados_mensais()                   TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.sync_leads_to_dados_comerciais()                 TO PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.sync_leads_to_origem_leads()                     TO PUBLIC, anon, authenticated;

-- -----------------------------------------------------------------------------
-- BASELINE DAS 95 FUNÇÕES AINDA NÃO TOCADAS (Sprints 2-6)
-- Estado EXATO do EXECUTE em 2026-06-30 (reproduz PUBLIC/anon/authenticated/
-- service_role/postgres conforme cada função tinha). Para reverter qualquer
-- sprint futuro, localize as funções do sprint e rode os GRANTs abaixo delas.
-- -----------------------------------------------------------------------------
GRANT EXECUTE ON FUNCTION public.admin_conversa_nova_mensagem(p_conversa_id uuid, p_preview text, p_whatsapp_jid text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_conversa_nova_mensagem(p_conversa_id uuid, p_preview text, p_whatsapp_jid text) TO anon;
GRANT EXECUTE ON FUNCTION public.admin_conversa_nova_mensagem(p_conversa_id uuid, p_preview text, p_whatsapp_jid text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_conversa_nova_mensagem(p_conversa_id uuid, p_preview text, p_whatsapp_jid text) TO postgres;
GRANT EXECUTE ON FUNCTION public.admin_conversa_nova_mensagem(p_conversa_id uuid, p_preview text, p_whatsapp_jid text) TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_update_user_password(target_user_id uuid, new_password text) TO anon;
GRANT EXECUTE ON FUNCTION public.admin_update_user_password(target_user_id uuid, new_password text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_update_user_password(target_user_id uuid, new_password text) TO postgres;
GRANT EXECUTE ON FUNCTION public.admin_update_user_password(target_user_id uuid, new_password text) TO service_role;
GRANT EXECUTE ON FUNCTION public.ajustar_estoque_manual(p_produto_id integer, p_unidade_id uuid, p_delta integer, p_motivo text, p_via_audit text, p_variacao_id integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.ajustar_estoque_manual(p_produto_id integer, p_unidade_id uuid, p_delta integer, p_motivo text, p_via_audit text, p_variacao_id integer) TO anon;
GRANT EXECUTE ON FUNCTION public.ajustar_estoque_manual(p_produto_id integer, p_unidade_id uuid, p_delta integer, p_motivo text, p_via_audit text, p_variacao_id integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.ajustar_estoque_manual(p_produto_id integer, p_unidade_id uuid, p_delta integer, p_motivo text, p_via_audit text, p_variacao_id integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.ajustar_estoque_manual(p_produto_id integer, p_unidade_id uuid, p_delta integer, p_motivo text, p_via_audit text, p_variacao_id integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.aplicar_conciliacao_aluno_atributo(p_divergencia_id bigint, p_decisao text, p_decidido_por text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.aplicar_conciliacao_aluno_atributo(p_divergencia_id bigint, p_decisao text, p_decidido_por text) TO anon;
GRANT EXECUTE ON FUNCTION public.aplicar_conciliacao_aluno_atributo(p_divergencia_id bigint, p_decisao text, p_decidido_por text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.aplicar_conciliacao_aluno_atributo(p_divergencia_id bigint, p_decisao text, p_decidido_por text) TO postgres;
GRANT EXECUTE ON FUNCTION public.aplicar_conciliacao_aluno_atributo(p_divergencia_id bigint, p_decisao text, p_decidido_por text) TO service_role;
GRANT EXECUTE ON FUNCTION public.aplicar_conciliacao_decisao(p_divergencia_id bigint, p_aluno_id integer, p_decisao text, p_patch jsonb, p_emusys_matricula_id text, p_decidido_por text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.aplicar_conciliacao_decisao(p_divergencia_id bigint, p_aluno_id integer, p_decisao text, p_patch jsonb, p_emusys_matricula_id text, p_decidido_por text) TO anon;
GRANT EXECUTE ON FUNCTION public.aplicar_conciliacao_decisao(p_divergencia_id bigint, p_aluno_id integer, p_decisao text, p_patch jsonb, p_emusys_matricula_id text, p_decidido_por text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.aplicar_conciliacao_decisao(p_divergencia_id bigint, p_aluno_id integer, p_decisao text, p_patch jsonb, p_emusys_matricula_id text, p_decidido_por text) TO postgres;
GRANT EXECUTE ON FUNCTION public.aplicar_conciliacao_decisao(p_divergencia_id bigint, p_aluno_id integer, p_decisao text, p_patch jsonb, p_emusys_matricula_id text, p_decidido_por text) TO service_role;
GRANT EXECUTE ON FUNCTION public.atualizar_config_fideliza(p_ano integer, p_campo character varying, p_valor text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.atualizar_config_fideliza(p_ano integer, p_campo character varying, p_valor text) TO anon;
GRANT EXECUTE ON FUNCTION public.atualizar_config_fideliza(p_ano integer, p_campo character varying, p_valor text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.atualizar_config_fideliza(p_ano integer, p_campo character varying, p_valor text) TO postgres;
GRANT EXECUTE ON FUNCTION public.atualizar_config_fideliza(p_ano integer, p_campo character varying, p_valor text) TO service_role;
GRANT EXECUTE ON FUNCTION public.atualizar_config_matriculador(p_ano integer, p_config jsonb) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.atualizar_config_matriculador(p_ano integer, p_config jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.atualizar_config_matriculador(p_ano integer, p_config jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.atualizar_config_matriculador(p_ano integer, p_config jsonb) TO postgres;
GRANT EXECUTE ON FUNCTION public.atualizar_config_matriculador(p_ano integer, p_config jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.atualizar_health_score(p_aluno_id integer, p_professor_id integer, p_health_score character varying, p_observacao text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.atualizar_health_score(p_aluno_id integer, p_professor_id integer, p_health_score character varying, p_observacao text) TO anon;
GRANT EXECUTE ON FUNCTION public.atualizar_health_score(p_aluno_id integer, p_professor_id integer, p_health_score character varying, p_observacao text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.atualizar_health_score(p_aluno_id integer, p_professor_id integer, p_health_score character varying, p_observacao text) TO postgres;
GRANT EXECUTE ON FUNCTION public.atualizar_health_score(p_aluno_id integer, p_professor_id integer, p_health_score character varying, p_observacao text) TO service_role;
GRANT EXECUTE ON FUNCTION public.atualizar_lead_experimental(p_telefone text, p_nome text, p_unidade_id uuid, p_status text, p_etapa integer, p_data_experimental date, p_horario_experimental time without time zone, p_professor_id integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.atualizar_lead_experimental(p_telefone text, p_nome text, p_unidade_id uuid, p_status text, p_etapa integer, p_data_experimental date, p_horario_experimental time without time zone, p_professor_id integer) TO anon;
GRANT EXECUTE ON FUNCTION public.atualizar_lead_experimental(p_telefone text, p_nome text, p_unidade_id uuid, p_status text, p_etapa integer, p_data_experimental date, p_horario_experimental time without time zone, p_professor_id integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.atualizar_lead_experimental(p_telefone text, p_nome text, p_unidade_id uuid, p_status text, p_etapa integer, p_data_experimental date, p_horario_experimental time without time zone, p_professor_id integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.atualizar_lead_experimental(p_telefone text, p_nome text, p_unidade_id uuid, p_status text, p_etapa integer, p_data_experimental date, p_horario_experimental time without time zone, p_professor_id integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.atualizar_percentual_presenca(p_unidade_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.atualizar_percentual_presenca(p_unidade_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.atualizar_percentual_presenca(p_unidade_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.atualizar_percentual_presenca(p_unidade_id uuid) TO postgres;
GRANT EXECUTE ON FUNCTION public.atualizar_percentual_presenca(p_unidade_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.auditar_saude_conversas() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.auditar_saude_conversas() TO anon;
GRANT EXECUTE ON FUNCTION public.auditar_saude_conversas() TO authenticated;
GRANT EXECUTE ON FUNCTION public.auditar_saude_conversas() TO postgres;
GRANT EXECUTE ON FUNCTION public.auditar_saude_conversas() TO service_role;
GRANT EXECUTE ON FUNCTION public.buscar_anamnese_pendente(p_nome text, p_unidade_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.buscar_anamnese_pendente(p_nome text, p_unidade_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.buscar_anamnese_pendente(p_nome text, p_unidade_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.buscar_anamnese_pendente(p_nome text, p_unidade_id uuid) TO postgres;
GRANT EXECUTE ON FUNCTION public.buscar_anamnese_pendente(p_nome text, p_unidade_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.buscar_anamneses_pendentes(p_aluno_id integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.buscar_anamneses_pendentes(p_aluno_id integer) TO anon;
GRANT EXECUTE ON FUNCTION public.buscar_anamneses_pendentes(p_aluno_id integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.buscar_anamneses_pendentes(p_aluno_id integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.buscar_anamneses_pendentes(p_aluno_id integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.buscar_anamneses_pendentes_todas(p_unidade_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.buscar_anamneses_pendentes_todas(p_unidade_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.buscar_anamneses_pendentes_todas(p_unidade_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.buscar_anamneses_pendentes_todas(p_unidade_id uuid) TO postgres;
GRANT EXECUTE ON FUNCTION public.buscar_anamneses_pendentes_todas(p_unidade_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.buscar_produto_fuzzy(p_termo text, p_unidade_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.buscar_produto_fuzzy(p_termo text, p_unidade_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.buscar_produto_fuzzy(p_termo text, p_unidade_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.buscar_produto_fuzzy(p_termo text, p_unidade_id uuid) TO postgres;
GRANT EXECUTE ON FUNCTION public.buscar_produto_fuzzy(p_termo text, p_unidade_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.buscar_video_professor(p_nome_professor text, p_nome_curso text, p_tipo text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.buscar_video_professor(p_nome_professor text, p_nome_curso text, p_tipo text) TO anon;
GRANT EXECUTE ON FUNCTION public.buscar_video_professor(p_nome_professor text, p_nome_curso text, p_tipo text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.buscar_video_professor(p_nome_professor text, p_nome_curso text, p_tipo text) TO postgres;
GRANT EXECUTE ON FUNCTION public.buscar_video_professor(p_nome_professor text, p_nome_curso text, p_tipo text) TO service_role;
GRANT EXECUTE ON FUNCTION public.calcular_health_score_aluno(p_aluno_id integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.calcular_health_score_aluno(p_aluno_id integer) TO anon;
GRANT EXECUTE ON FUNCTION public.calcular_health_score_aluno(p_aluno_id integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.calcular_health_score_aluno(p_aluno_id integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.calcular_health_score_aluno(p_aluno_id integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.calcular_health_score_alunos_batch(p_unidade_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.calcular_health_score_alunos_batch(p_unidade_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.calcular_health_score_alunos_batch(p_unidade_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.calcular_health_score_alunos_batch(p_unidade_id uuid) TO postgres;
GRANT EXECUTE ON FUNCTION public.calcular_health_score_alunos_batch(p_unidade_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.calcular_tempo_medio_resposta_crm(p_inicio text, p_fim text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.calcular_tempo_medio_resposta_crm(p_inicio text, p_fim text) TO anon;
GRANT EXECUTE ON FUNCTION public.calcular_tempo_medio_resposta_crm(p_inicio text, p_fim text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.calcular_tempo_medio_resposta_crm(p_inicio text, p_fim text) TO postgres;
GRANT EXECUTE ON FUNCTION public.calcular_tempo_medio_resposta_crm(p_inicio text, p_fim text) TO service_role;
GRANT EXECUTE ON FUNCTION public.campo_fixado(p_aluno_id integer, p_campo text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.campo_fixado(p_aluno_id integer, p_campo text) TO anon;
GRANT EXECUTE ON FUNCTION public.campo_fixado(p_aluno_id integer, p_campo text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.campo_fixado(p_aluno_id integer, p_campo text) TO postgres;
GRANT EXECUTE ON FUNCTION public.campo_fixado(p_aluno_id integer, p_campo text) TO service_role;
GRANT EXECUTE ON FUNCTION public.cleanup_bi_conversations() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.cleanup_bi_conversations() TO anon;
GRANT EXECUTE ON FUNCTION public.cleanup_bi_conversations() TO authenticated;
GRANT EXECUTE ON FUNCTION public.cleanup_bi_conversations() TO postgres;
GRANT EXECUTE ON FUNCTION public.cleanup_bi_conversations() TO service_role;
GRANT EXECUTE ON FUNCTION public.criar_checklist_from_template(p_template_id uuid, p_colaborador_id integer, p_unidade_id uuid, p_titulo character varying, p_data_prazo date) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.criar_checklist_from_template(p_template_id uuid, p_colaborador_id integer, p_unidade_id uuid, p_titulo character varying, p_data_prazo date) TO anon;
GRANT EXECUTE ON FUNCTION public.criar_checklist_from_template(p_template_id uuid, p_colaborador_id integer, p_unidade_id uuid, p_titulo character varying, p_data_prazo date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.criar_checklist_from_template(p_template_id uuid, p_colaborador_id integer, p_unidade_id uuid, p_titulo character varying, p_data_prazo date) TO postgres;
GRANT EXECUTE ON FUNCTION public.criar_checklist_from_template(p_template_id uuid, p_colaborador_id integer, p_unidade_id uuid, p_titulo character varying, p_data_prazo date) TO service_role;
GRANT EXECUTE ON FUNCTION public.criar_conversa_lead(p_lead_id integer, p_atribuido_a character varying) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.criar_conversa_lead(p_lead_id integer, p_atribuido_a character varying) TO anon;
GRANT EXECUTE ON FUNCTION public.criar_conversa_lead(p_lead_id integer, p_atribuido_a character varying) TO authenticated;
GRANT EXECUTE ON FUNCTION public.criar_conversa_lead(p_lead_id integer, p_atribuido_a character varying) TO postgres;
GRANT EXECUTE ON FUNCTION public.criar_conversa_lead(p_lead_id integer, p_atribuido_a character varying) TO service_role;
GRANT EXECUTE ON FUNCTION public.deletar_penalidade_fideliza(p_id integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.deletar_penalidade_fideliza(p_id integer) TO anon;
GRANT EXECUTE ON FUNCTION public.deletar_penalidade_fideliza(p_id integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.deletar_penalidade_fideliza(p_id integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.deletar_penalidade_fideliza(p_id integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.deletar_penalidade_matriculador(p_id integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.deletar_penalidade_matriculador(p_id integer) TO anon;
GRANT EXECUTE ON FUNCTION public.deletar_penalidade_matriculador(p_id integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.deletar_penalidade_matriculador(p_id integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.deletar_penalidade_matriculador(p_id integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.editar_ocorrencia(p_ocorrencia_id integer, p_usuario_id uuid, p_usuario_nome character varying, p_justificativa text, p_data_ocorrencia date, p_descricao text, p_minutos_atraso integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.editar_ocorrencia(p_ocorrencia_id integer, p_usuario_id uuid, p_usuario_nome character varying, p_justificativa text, p_data_ocorrencia date, p_descricao text, p_minutos_atraso integer) TO anon;
GRANT EXECUTE ON FUNCTION public.editar_ocorrencia(p_ocorrencia_id integer, p_usuario_id uuid, p_usuario_nome character varying, p_justificativa text, p_data_ocorrencia date, p_descricao text, p_minutos_atraso integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.editar_ocorrencia(p_ocorrencia_id integer, p_usuario_id uuid, p_usuario_nome character varying, p_justificativa text, p_data_ocorrencia date, p_descricao text, p_minutos_atraso integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.editar_ocorrencia(p_ocorrencia_id integer, p_usuario_id uuid, p_usuario_nome character varying, p_justificativa text, p_data_ocorrencia date, p_descricao text, p_minutos_atraso integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.estoque_disponivel(p_produto_id integer, p_unidade_id uuid, p_variacao_id integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.estoque_disponivel(p_produto_id integer, p_unidade_id uuid, p_variacao_id integer) TO anon;
GRANT EXECUTE ON FUNCTION public.estoque_disponivel(p_produto_id integer, p_unidade_id uuid, p_variacao_id integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.estoque_disponivel(p_produto_id integer, p_unidade_id uuid, p_variacao_id integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.estoque_disponivel(p_produto_id integer, p_unidade_id uuid, p_variacao_id integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.estornar_venda(p_venda_id integer, p_motivo text, p_via_audit text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.estornar_venda(p_venda_id integer, p_motivo text, p_via_audit text) TO anon;
GRANT EXECUTE ON FUNCTION public.estornar_venda(p_venda_id integer, p_motivo text, p_via_audit text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.estornar_venda(p_venda_id integer, p_motivo text, p_via_audit text) TO postgres;
GRANT EXECUTE ON FUNCTION public.estornar_venda(p_venda_id integer, p_motivo text, p_via_audit text) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_anamnese_by_token(p_token character varying) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_anamnese_by_token(p_token character varying) TO anon;
GRANT EXECUTE ON FUNCTION public.get_anamnese_by_token(p_token character varying) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_anamnese_by_token(p_token character varying) TO postgres;
GRANT EXECUTE ON FUNCTION public.get_anamnese_by_token(p_token character varying) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_anamnese_publica(p_token text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_anamnese_publica(p_token text) TO anon;
GRANT EXECUTE ON FUNCTION public.get_anamnese_publica(p_token text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_anamnese_publica(p_token text) TO postgres;
GRANT EXECUTE ON FUNCTION public.get_anamnese_publica(p_token text) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_checklist_detail(p_checklist_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_checklist_detail(p_checklist_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_checklist_detail(p_checklist_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_checklist_detail(p_checklist_id uuid) TO postgres;
GRANT EXECUTE ON FUNCTION public.get_checklist_detail(p_checklist_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_conciliacao_matriculas(p_unidade_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_conciliacao_matriculas(p_unidade_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_conciliacao_matriculas(p_unidade_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_conciliacao_matriculas(p_unidade_id uuid) TO postgres;
GRANT EXECUTE ON FUNCTION public.get_conciliacao_matriculas(p_unidade_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_conciliacao_professores_emusys(p_unidade_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_conciliacao_professores_emusys(p_unidade_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_conciliacao_professores_emusys(p_unidade_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_conciliacao_professores_emusys(p_unidade_id uuid) TO postgres;
GRANT EXECUTE ON FUNCTION public.get_conciliacao_professores_emusys(p_unidade_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_cron_health() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_cron_health() TO anon;
GRANT EXECUTE ON FUNCTION public.get_cron_health() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_cron_health() TO postgres;
GRANT EXECUTE ON FUNCTION public.get_cron_health() TO service_role;
GRANT EXECUTE ON FUNCTION public.get_dados_relatorio_coordenacao(p_unidade_id uuid, p_ano integer, p_mes integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_dados_relatorio_coordenacao(p_unidade_id uuid, p_ano integer, p_mes integer) TO anon;
GRANT EXECUTE ON FUNCTION public.get_dados_relatorio_coordenacao(p_unidade_id uuid, p_ano integer, p_mes integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_dados_relatorio_coordenacao(p_unidade_id uuid, p_ano integer, p_mes integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.get_dados_relatorio_coordenacao(p_unidade_id uuid, p_ano integer, p_mes integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_divergencias_alunos() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_divergencias_alunos() TO anon;
GRANT EXECUTE ON FUNCTION public.get_divergencias_alunos() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_divergencias_alunos() TO postgres;
GRANT EXECUTE ON FUNCTION public.get_divergencias_alunos() TO service_role;
GRANT EXECUTE ON FUNCTION public.get_fabio_aulas_do_professor(p_unidade_id uuid, p_emusys_professor_id integer, p_data_aula date) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_fabio_aulas_do_professor(p_unidade_id uuid, p_emusys_professor_id integer, p_data_aula date) TO anon;
GRANT EXECUTE ON FUNCTION public.get_fabio_aulas_do_professor(p_unidade_id uuid, p_emusys_professor_id integer, p_data_aula date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_fabio_aulas_do_professor(p_unidade_id uuid, p_emusys_professor_id integer, p_data_aula date) TO postgres;
GRANT EXECUTE ON FUNCTION public.get_fabio_aulas_do_professor(p_unidade_id uuid, p_emusys_professor_id integer, p_data_aula date) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_faltas_periodo(p_unidade_id uuid, p_data_inicio date, p_data_fim date) TO anon;
GRANT EXECUTE ON FUNCTION public.get_faltas_periodo(p_unidade_id uuid, p_data_inicio date, p_data_fim date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_faltas_periodo(p_unidade_id uuid, p_data_inicio date, p_data_fim date) TO postgres;
GRANT EXECUTE ON FUNCTION public.get_faltas_periodo(p_unidade_id uuid, p_data_inicio date, p_data_fim date) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_historico_ltv(p_unidade_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_historico_ltv(p_unidade_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_historico_ltv(p_unidade_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_historico_ltv(p_unidade_id uuid) TO postgres;
GRANT EXECUTE ON FUNCTION public.get_historico_ltv(p_unidade_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_historico_rotinas(p_colaborador_id integer, p_dias integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_historico_rotinas(p_colaborador_id integer, p_dias integer) TO anon;
GRANT EXECUTE ON FUNCTION public.get_historico_rotinas(p_colaborador_id integer, p_dias integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_historico_rotinas(p_colaborador_id integer, p_dias integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.get_historico_rotinas(p_colaborador_id integer, p_dias integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_kpis_consolidados(p_ano integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_kpis_consolidados(p_ano integer) TO anon;
GRANT EXECUTE ON FUNCTION public.get_kpis_consolidados(p_ano integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_kpis_consolidados(p_ano integer) TO maria_lareport_rpc;
GRANT EXECUTE ON FUNCTION public.get_kpis_consolidados(p_ano integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.get_kpis_consolidados(p_ano integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_kpis_evolucao_mensal(p_unidade_id text, p_meses integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_kpis_evolucao_mensal(p_unidade_id text, p_meses integer) TO anon;
GRANT EXECUTE ON FUNCTION public.get_kpis_evolucao_mensal(p_unidade_id text, p_meses integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_kpis_evolucao_mensal(p_unidade_id text, p_meses integer) TO maria_lareport_rpc;
GRANT EXECUTE ON FUNCTION public.get_kpis_evolucao_mensal(p_unidade_id text, p_meses integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.get_kpis_evolucao_mensal(p_unidade_id text, p_meses integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_kpis_experimentais_professor(p_ano integer, p_mes integer, p_unidade_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_kpis_experimentais_professor(p_ano integer, p_mes integer, p_unidade_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_kpis_experimentais_professor(p_ano integer, p_mes integer, p_unidade_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_kpis_experimentais_professor(p_ano integer, p_mes integer, p_unidade_id uuid) TO maria_lareport_rpc;
GRANT EXECUTE ON FUNCTION public.get_kpis_experimentais_professor(p_ano integer, p_mes integer, p_unidade_id uuid) TO postgres;
GRANT EXECUTE ON FUNCTION public.get_kpis_experimentais_professor(p_ano integer, p_mes integer, p_unidade_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_kpis_unidade(p_unidade_codigo character varying, p_ano integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_kpis_unidade(p_unidade_codigo character varying, p_ano integer) TO anon;
GRANT EXECUTE ON FUNCTION public.get_kpis_unidade(p_unidade_codigo character varying, p_ano integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_kpis_unidade(p_unidade_codigo character varying, p_ano integer) TO maria_lareport_rpc;
GRANT EXECUTE ON FUNCTION public.get_kpis_unidade(p_unidade_codigo character varying, p_ano integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.get_kpis_unidade(p_unidade_codigo character varying, p_ano integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_programa_fideliza_dados(p_ano integer, p_trimestre integer, p_unidade_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_programa_fideliza_dados(p_ano integer, p_trimestre integer, p_unidade_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_programa_fideliza_dados(p_ano integer, p_trimestre integer, p_unidade_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_programa_fideliza_dados(p_ano integer, p_trimestre integer, p_unidade_id uuid) TO postgres;
GRANT EXECUTE ON FUNCTION public.get_programa_fideliza_dados(p_ano integer, p_trimestre integer, p_unidade_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_progresso_rotinas_hoje(p_colaborador_id integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_progresso_rotinas_hoje(p_colaborador_id integer) TO anon;
GRANT EXECUTE ON FUNCTION public.get_progresso_rotinas_hoje(p_colaborador_id integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_progresso_rotinas_hoje(p_colaborador_id integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.get_progresso_rotinas_hoje(p_colaborador_id integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_resumo_renovacoes_proximas(p_unidade_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_resumo_renovacoes_proximas(p_unidade_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_resumo_renovacoes_proximas(p_unidade_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_resumo_renovacoes_proximas(p_unidade_id uuid) TO maria_lareport_rpc;
GRANT EXECUTE ON FUNCTION public.get_resumo_renovacoes_proximas(p_unidade_id uuid) TO postgres;
GRANT EXECUTE ON FUNCTION public.get_resumo_renovacoes_proximas(p_unidade_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_rotinas_do_dia(p_colaborador_id integer, p_data date) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_rotinas_do_dia(p_colaborador_id integer, p_data date) TO anon;
GRANT EXECUTE ON FUNCTION public.get_rotinas_do_dia(p_colaborador_id integer, p_data date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_rotinas_do_dia(p_colaborador_id integer, p_data date) TO postgres;
GRANT EXECUTE ON FUNCTION public.get_rotinas_do_dia(p_colaborador_id integer, p_data date) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_tempo_permanencia(p_unidade_id uuid, p_ano integer, p_mes integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_tempo_permanencia(p_unidade_id uuid, p_ano integer, p_mes integer) TO anon;
GRANT EXECUTE ON FUNCTION public.get_tempo_permanencia(p_unidade_id uuid, p_ano integer, p_mes integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_tempo_permanencia(p_unidade_id uuid, p_ano integer, p_mes integer) TO maria_lareport_rpc;
GRANT EXECUTE ON FUNCTION public.get_tempo_permanencia(p_unidade_id uuid, p_ano integer, p_mes integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.get_tempo_permanencia(p_unidade_id uuid, p_ano integer, p_mes integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_timeline_pesquisas_aluno(p_aluno_id integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_timeline_pesquisas_aluno(p_aluno_id integer) TO anon;
GRANT EXECUTE ON FUNCTION public.get_timeline_pesquisas_aluno(p_aluno_id integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_timeline_pesquisas_aluno(p_aluno_id integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.get_timeline_pesquisas_aluno(p_aluno_id integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_unidade_usuario() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_unidade_usuario() TO anon;
GRANT EXECUTE ON FUNCTION public.get_unidade_usuario() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_unidade_usuario() TO postgres;
GRANT EXECUTE ON FUNCTION public.get_unidade_usuario() TO service_role;
GRANT EXECUTE ON FUNCTION public.get_user_unidade_id() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_user_unidade_id() TO anon;
GRANT EXECUTE ON FUNCTION public.get_user_unidade_id() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_user_unidade_id() TO postgres;
GRANT EXECUTE ON FUNCTION public.get_user_unidade_id() TO service_role;
GRANT EXECUTE ON FUNCTION public.ignorar_conciliacao_aluno_atributo(p_divergencia_id bigint, p_decidido_por text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.ignorar_conciliacao_aluno_atributo(p_divergencia_id bigint, p_decidido_por text) TO anon;
GRANT EXECUTE ON FUNCTION public.ignorar_conciliacao_aluno_atributo(p_divergencia_id bigint, p_decidido_por text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.ignorar_conciliacao_aluno_atributo(p_divergencia_id bigint, p_decidido_por text) TO postgres;
GRANT EXECUTE ON FUNCTION public.ignorar_conciliacao_aluno_atributo(p_divergencia_id bigint, p_decidido_por text) TO service_role;
GRANT EXECUTE ON FUNCTION public.is_admin() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_admin() TO anon;
GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_admin() TO postgres;
GRANT EXECUTE ON FUNCTION public.is_admin() TO service_role;
GRANT EXECUTE ON FUNCTION public.is_admin_usuario() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_admin_usuario() TO anon;
GRANT EXECUTE ON FUNCTION public.is_admin_usuario() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_admin_usuario() TO postgres;
GRANT EXECUTE ON FUNCTION public.is_admin_usuario() TO service_role;
GRANT EXECUTE ON FUNCTION public.is_movimentacao_admin_retencao_valida(p_movimentacao_id integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_movimentacao_admin_retencao_valida(p_movimentacao_id integer) TO anon;
GRANT EXECUTE ON FUNCTION public.is_movimentacao_admin_retencao_valida(p_movimentacao_id integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_movimentacao_admin_retencao_valida(p_movimentacao_id integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.is_movimentacao_admin_retencao_valida(p_movimentacao_id integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.limpar_mila_buffer_antigo() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.limpar_mila_buffer_antigo() TO anon;
GRANT EXECUTE ON FUNCTION public.limpar_mila_buffer_antigo() TO authenticated;
GRANT EXECUTE ON FUNCTION public.limpar_mila_buffer_antigo() TO postgres;
GRANT EXECUTE ON FUNCTION public.limpar_mila_buffer_antigo() TO service_role;
GRANT EXECUTE ON FUNCTION public.limpar_professores_emusys_divergencias_obsoletas() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.limpar_professores_emusys_divergencias_obsoletas() TO anon;
GRANT EXECUTE ON FUNCTION public.limpar_professores_emusys_divergencias_obsoletas() TO authenticated;
GRANT EXECUTE ON FUNCTION public.limpar_professores_emusys_divergencias_obsoletas() TO postgres;
GRANT EXECUTE ON FUNCTION public.limpar_professores_emusys_divergencias_obsoletas() TO service_role;
GRANT EXECUTE ON FUNCTION public.marcar_checklist_item(p_item_id uuid, p_concluida boolean, p_colaborador_id integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.marcar_checklist_item(p_item_id uuid, p_concluida boolean, p_colaborador_id integer) TO anon;
GRANT EXECUTE ON FUNCTION public.marcar_checklist_item(p_item_id uuid, p_concluida boolean, p_colaborador_id integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.marcar_checklist_item(p_item_id uuid, p_concluida boolean, p_colaborador_id integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.marcar_checklist_item(p_item_id uuid, p_concluida boolean, p_colaborador_id integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.marcar_conversa_lida(p_conversa_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.marcar_conversa_lida(p_conversa_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.marcar_conversa_lida(p_conversa_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.marcar_conversa_lida(p_conversa_id uuid) TO postgres;
GRANT EXECUTE ON FUNCTION public.marcar_conversa_lida(p_conversa_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.marcar_inadimplentes_apos_vencimento() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.marcar_inadimplentes_apos_vencimento() TO anon;
GRANT EXECUTE ON FUNCTION public.marcar_inadimplentes_apos_vencimento() TO authenticated;
GRANT EXECUTE ON FUNCTION public.marcar_inadimplentes_apos_vencimento() TO postgres;
GRANT EXECUTE ON FUNCTION public.marcar_inadimplentes_apos_vencimento() TO service_role;
GRANT EXECUTE ON FUNCTION public.marcar_rotina_concluida(p_rotina_id uuid, p_colaborador_id integer, p_concluida boolean, p_data date) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.marcar_rotina_concluida(p_rotina_id uuid, p_colaborador_id integer, p_concluida boolean, p_data date) TO anon;
GRANT EXECUTE ON FUNCTION public.marcar_rotina_concluida(p_rotina_id uuid, p_colaborador_id integer, p_concluida boolean, p_data date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.marcar_rotina_concluida(p_rotina_id uuid, p_colaborador_id integer, p_concluida boolean, p_data date) TO postgres;
GRANT EXECUTE ON FUNCTION public.marcar_rotina_concluida(p_rotina_id uuid, p_colaborador_id integer, p_concluida boolean, p_data date) TO service_role;
GRANT EXECUTE ON FUNCTION public.maria_lareport_buscar_alunos(p_busca text, p_unidade_id uuid, p_limit integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.maria_lareport_buscar_alunos(p_busca text, p_unidade_id uuid, p_limit integer) TO anon;
GRANT EXECUTE ON FUNCTION public.maria_lareport_buscar_alunos(p_busca text, p_unidade_id uuid, p_limit integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.maria_lareport_buscar_alunos(p_busca text, p_unidade_id uuid, p_limit integer) TO maria_lareport_rpc;
GRANT EXECUTE ON FUNCTION public.maria_lareport_buscar_alunos(p_busca text, p_unidade_id uuid, p_limit integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.maria_lareport_buscar_alunos(p_busca text, p_unidade_id uuid, p_limit integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.maria_lareport_consultor_matriculas_mes(p_unidade_id uuid, p_ano integer, p_mes integer, p_limit integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.maria_lareport_consultor_matriculas_mes(p_unidade_id uuid, p_ano integer, p_mes integer, p_limit integer) TO anon;
GRANT EXECUTE ON FUNCTION public.maria_lareport_consultor_matriculas_mes(p_unidade_id uuid, p_ano integer, p_mes integer, p_limit integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.maria_lareport_consultor_matriculas_mes(p_unidade_id uuid, p_ano integer, p_mes integer, p_limit integer) TO maria_lareport_rpc;
GRANT EXECUTE ON FUNCTION public.maria_lareport_consultor_matriculas_mes(p_unidade_id uuid, p_ano integer, p_mes integer, p_limit integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.maria_lareport_consultor_matriculas_mes(p_unidade_id uuid, p_ano integer, p_mes integer, p_limit integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.maria_lareport_evasoes_mes_detalhe(p_unidade_id uuid, p_ano integer, p_mes integer, p_limit integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.maria_lareport_evasoes_mes_detalhe(p_unidade_id uuid, p_ano integer, p_mes integer, p_limit integer) TO anon;
GRANT EXECUTE ON FUNCTION public.maria_lareport_evasoes_mes_detalhe(p_unidade_id uuid, p_ano integer, p_mes integer, p_limit integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.maria_lareport_evasoes_mes_detalhe(p_unidade_id uuid, p_ano integer, p_mes integer, p_limit integer) TO maria_lareport_rpc;
GRANT EXECUTE ON FUNCTION public.maria_lareport_evasoes_mes_detalhe(p_unidade_id uuid, p_ano integer, p_mes integer, p_limit integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.maria_lareport_evasoes_mes_detalhe(p_unidade_id uuid, p_ano integer, p_mes integer, p_limit integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.maria_lareport_matriculas_mes_detalhe(p_unidade_id uuid, p_ano integer, p_mes integer, p_limit integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.maria_lareport_matriculas_mes_detalhe(p_unidade_id uuid, p_ano integer, p_mes integer, p_limit integer) TO anon;
GRANT EXECUTE ON FUNCTION public.maria_lareport_matriculas_mes_detalhe(p_unidade_id uuid, p_ano integer, p_mes integer, p_limit integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.maria_lareport_matriculas_mes_detalhe(p_unidade_id uuid, p_ano integer, p_mes integer, p_limit integer) TO maria_lareport_rpc;
GRANT EXECUTE ON FUNCTION public.maria_lareport_matriculas_mes_detalhe(p_unidade_id uuid, p_ano integer, p_mes integer, p_limit integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.maria_lareport_matriculas_mes_detalhe(p_unidade_id uuid, p_ano integer, p_mes integer, p_limit integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.maria_lareport_professor_carteira(p_unidade_id uuid, p_professor_busca text, p_limit integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.maria_lareport_professor_carteira(p_unidade_id uuid, p_professor_busca text, p_limit integer) TO anon;
GRANT EXECUTE ON FUNCTION public.maria_lareport_professor_carteira(p_unidade_id uuid, p_professor_busca text, p_limit integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.maria_lareport_professor_carteira(p_unidade_id uuid, p_professor_busca text, p_limit integer) TO maria_lareport_rpc;
GRANT EXECUTE ON FUNCTION public.maria_lareport_professor_carteira(p_unidade_id uuid, p_professor_busca text, p_limit integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.maria_lareport_professor_carteira(p_unidade_id uuid, p_professor_busca text, p_limit integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.mila_check_disponibilidade_visita(p_unidade_id uuid, p_data date, p_horario time without time zone, p_telefone text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mila_check_disponibilidade_visita(p_unidade_id uuid, p_data date, p_horario time without time zone, p_telefone text) TO anon;
GRANT EXECUTE ON FUNCTION public.mila_check_disponibilidade_visita(p_unidade_id uuid, p_data date, p_horario time without time zone, p_telefone text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mila_check_disponibilidade_visita(p_unidade_id uuid, p_data date, p_horario time without time zone, p_telefone text) TO postgres;
GRANT EXECUTE ON FUNCTION public.mila_check_disponibilidade_visita(p_unidade_id uuid, p_data date, p_horario time without time zone, p_telefone text) TO service_role;
GRANT EXECUTE ON FUNCTION public.reabrir_caixa_diario(p_caixa_diario_id uuid, p_motivo text, p_reaberto_por text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.reabrir_caixa_diario(p_caixa_diario_id uuid, p_motivo text, p_reaberto_por text) TO anon;
GRANT EXECUTE ON FUNCTION public.reabrir_caixa_diario(p_caixa_diario_id uuid, p_motivo text, p_reaberto_por text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reabrir_caixa_diario(p_caixa_diario_id uuid, p_motivo text, p_reaberto_por text) TO postgres;
GRANT EXECUTE ON FUNCTION public.reabrir_caixa_diario(p_caixa_diario_id uuid, p_motivo text, p_reaberto_por text) TO service_role;
GRANT EXECUTE ON FUNCTION public.registrar_aula_fabio(p_aula_id integer, p_texto text, p_origem text, p_professor_id integer, p_modo text) TO anon;
GRANT EXECUTE ON FUNCTION public.registrar_aula_fabio(p_aula_id integer, p_texto text, p_origem text, p_professor_id integer, p_modo text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.registrar_aula_fabio(p_aula_id integer, p_texto text, p_origem text, p_professor_id integer, p_modo text) TO fabio_agent;
GRANT EXECUTE ON FUNCTION public.registrar_aula_fabio(p_aula_id integer, p_texto text, p_origem text, p_professor_id integer, p_modo text) TO postgres;
GRANT EXECUTE ON FUNCTION public.registrar_aula_fabio(p_aula_id integer, p_texto text, p_origem text, p_professor_id integer, p_modo text) TO service_role;
GRANT EXECUTE ON FUNCTION public.registrar_entrada_estoque(p_produto_id integer, p_unidade_id uuid, p_quantidade integer, p_via_audit text, p_variacao_id integer, p_observacoes text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.registrar_entrada_estoque(p_produto_id integer, p_unidade_id uuid, p_quantidade integer, p_via_audit text, p_variacao_id integer, p_observacoes text) TO anon;
GRANT EXECUTE ON FUNCTION public.registrar_entrada_estoque(p_produto_id integer, p_unidade_id uuid, p_quantidade integer, p_via_audit text, p_variacao_id integer, p_observacoes text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.registrar_entrada_estoque(p_produto_id integer, p_unidade_id uuid, p_quantidade integer, p_via_audit text, p_variacao_id integer, p_observacoes text) TO postgres;
GRANT EXECUTE ON FUNCTION public.registrar_entrada_estoque(p_produto_id integer, p_unidade_id uuid, p_quantidade integer, p_via_audit text, p_variacao_id integer, p_observacoes text) TO service_role;
GRANT EXECUTE ON FUNCTION public.registrar_entrada_estoque_v2(p_unidade_id uuid, p_itens jsonb, p_via_audit text, p_nf text, p_fornecedor text, p_observacoes text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.registrar_entrada_estoque_v2(p_unidade_id uuid, p_itens jsonb, p_via_audit text, p_nf text, p_fornecedor text, p_observacoes text) TO anon;
GRANT EXECUTE ON FUNCTION public.registrar_entrada_estoque_v2(p_unidade_id uuid, p_itens jsonb, p_via_audit text, p_nf text, p_fornecedor text, p_observacoes text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.registrar_entrada_estoque_v2(p_unidade_id uuid, p_itens jsonb, p_via_audit text, p_nf text, p_fornecedor text, p_observacoes text) TO postgres;
GRANT EXECUTE ON FUNCTION public.registrar_entrada_estoque_v2(p_unidade_id uuid, p_itens jsonb, p_via_audit text, p_nf text, p_fornecedor text, p_observacoes text) TO service_role;
GRANT EXECUTE ON FUNCTION public.registrar_experimental(p_telefone text, p_nome_aluno text, p_unidade_id uuid, p_status text, p_etapa integer, p_data_experimental date, p_horario_experimental time without time zone, p_professor_id integer, p_emusys_lead_id integer, p_created_at timestamp with time zone, p_curso text, p_emusys_aula_id integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.registrar_experimental(p_telefone text, p_nome_aluno text, p_unidade_id uuid, p_status text, p_etapa integer, p_data_experimental date, p_horario_experimental time without time zone, p_professor_id integer, p_emusys_lead_id integer, p_created_at timestamp with time zone, p_curso text, p_emusys_aula_id integer) TO anon;
GRANT EXECUTE ON FUNCTION public.registrar_experimental(p_telefone text, p_nome_aluno text, p_unidade_id uuid, p_status text, p_etapa integer, p_data_experimental date, p_horario_experimental time without time zone, p_professor_id integer, p_emusys_lead_id integer, p_created_at timestamp with time zone, p_curso text, p_emusys_aula_id integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.registrar_experimental(p_telefone text, p_nome_aluno text, p_unidade_id uuid, p_status text, p_etapa integer, p_data_experimental date, p_horario_experimental time without time zone, p_professor_id integer, p_emusys_lead_id integer, p_created_at timestamp with time zone, p_curso text, p_emusys_aula_id integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.registrar_experimental(p_telefone text, p_nome_aluno text, p_unidade_id uuid, p_status text, p_etapa integer, p_data_experimental date, p_horario_experimental time without time zone, p_professor_id integer, p_emusys_lead_id integer, p_created_at timestamp with time zone, p_curso text, p_emusys_aula_id integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.registrar_log_ocorrencia(p_ocorrencia_id integer, p_acao character varying, p_usuario_id uuid, p_usuario_nome character varying, p_justificativa text, p_dados_anteriores jsonb, p_dados_novos jsonb) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.registrar_log_ocorrencia(p_ocorrencia_id integer, p_acao character varying, p_usuario_id uuid, p_usuario_nome character varying, p_justificativa text, p_dados_anteriores jsonb, p_dados_novos jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.registrar_log_ocorrencia(p_ocorrencia_id integer, p_acao character varying, p_usuario_id uuid, p_usuario_nome character varying, p_justificativa text, p_dados_anteriores jsonb, p_dados_novos jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.registrar_log_ocorrencia(p_ocorrencia_id integer, p_acao character varying, p_usuario_id uuid, p_usuario_nome character varying, p_justificativa text, p_dados_anteriores jsonb, p_dados_novos jsonb) TO postgres;
GRANT EXECUTE ON FUNCTION public.registrar_log_ocorrencia(p_ocorrencia_id integer, p_acao character varying, p_usuario_id uuid, p_usuario_nome character varying, p_justificativa text, p_dados_anteriores jsonb, p_dados_novos jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.registrar_penalidade_fideliza(p_ano integer, p_trimestre integer, p_unidade_id uuid, p_tipo character varying, p_descricao text, p_pontos integer, p_data_ocorrencia date, p_registrado_por character varying) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.registrar_penalidade_fideliza(p_ano integer, p_trimestre integer, p_unidade_id uuid, p_tipo character varying, p_descricao text, p_pontos integer, p_data_ocorrencia date, p_registrado_por character varying) TO anon;
GRANT EXECUTE ON FUNCTION public.registrar_penalidade_fideliza(p_ano integer, p_trimestre integer, p_unidade_id uuid, p_tipo character varying, p_descricao text, p_pontos integer, p_data_ocorrencia date, p_registrado_por character varying) TO authenticated;
GRANT EXECUTE ON FUNCTION public.registrar_penalidade_fideliza(p_ano integer, p_trimestre integer, p_unidade_id uuid, p_tipo character varying, p_descricao text, p_pontos integer, p_data_ocorrencia date, p_registrado_por character varying) TO postgres;
GRANT EXECUTE ON FUNCTION public.registrar_penalidade_fideliza(p_ano integer, p_trimestre integer, p_unidade_id uuid, p_tipo character varying, p_descricao text, p_pontos integer, p_data_ocorrencia date, p_registrado_por character varying) TO service_role;
GRANT EXECUTE ON FUNCTION public.registrar_penalidade_matriculador(p_ano integer, p_unidade_id uuid, p_tipo character varying, p_descricao text, p_pontos integer, p_data_ocorrencia date, p_registrado_por character varying) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.registrar_penalidade_matriculador(p_ano integer, p_unidade_id uuid, p_tipo character varying, p_descricao text, p_pontos integer, p_data_ocorrencia date, p_registrado_por character varying) TO anon;
GRANT EXECUTE ON FUNCTION public.registrar_penalidade_matriculador(p_ano integer, p_unidade_id uuid, p_tipo character varying, p_descricao text, p_pontos integer, p_data_ocorrencia date, p_registrado_por character varying) TO authenticated;
GRANT EXECUTE ON FUNCTION public.registrar_penalidade_matriculador(p_ano integer, p_unidade_id uuid, p_tipo character varying, p_descricao text, p_pontos integer, p_data_ocorrencia date, p_registrado_por character varying) TO postgres;
GRANT EXECUTE ON FUNCTION public.registrar_penalidade_matriculador(p_ano integer, p_unidade_id uuid, p_tipo character varying, p_descricao text, p_pontos integer, p_data_ocorrencia date, p_registrado_por character varying) TO service_role;
GRANT EXECUTE ON FUNCTION public.registrar_resposta_pesquisa_manual(p_aluno_id integer, p_data date, p_tipo text, p_nota integer, p_comentario text, p_nao_respondeu boolean) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.registrar_resposta_pesquisa_manual(p_aluno_id integer, p_data date, p_tipo text, p_nota integer, p_comentario text, p_nao_respondeu boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.registrar_resposta_pesquisa_manual(p_aluno_id integer, p_data date, p_tipo text, p_nota integer, p_comentario text, p_nao_respondeu boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.registrar_resposta_pesquisa_manual(p_aluno_id integer, p_data date, p_tipo text, p_nota integer, p_comentario text, p_nao_respondeu boolean) TO postgres;
GRANT EXECUTE ON FUNCTION public.registrar_resposta_pesquisa_manual(p_aluno_id integer, p_data date, p_tipo text, p_nota integer, p_comentario text, p_nao_respondeu boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.registrar_venda_legacy(p_produto_id integer, p_unidade_id uuid, p_quantidade integer, p_forma_pagamento character varying, p_via_audit text, p_variacao_id integer, p_tipo_cliente character varying, p_cliente_nome character varying, p_aluno_id integer, p_professor_indicador_id integer, p_desconto numeric, p_parcelas integer, p_observacoes text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.registrar_venda_legacy(p_produto_id integer, p_unidade_id uuid, p_quantidade integer, p_forma_pagamento character varying, p_via_audit text, p_variacao_id integer, p_tipo_cliente character varying, p_cliente_nome character varying, p_aluno_id integer, p_professor_indicador_id integer, p_desconto numeric, p_parcelas integer, p_observacoes text) TO anon;
GRANT EXECUTE ON FUNCTION public.registrar_venda_legacy(p_produto_id integer, p_unidade_id uuid, p_quantidade integer, p_forma_pagamento character varying, p_via_audit text, p_variacao_id integer, p_tipo_cliente character varying, p_cliente_nome character varying, p_aluno_id integer, p_professor_indicador_id integer, p_desconto numeric, p_parcelas integer, p_observacoes text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.registrar_venda_legacy(p_produto_id integer, p_unidade_id uuid, p_quantidade integer, p_forma_pagamento character varying, p_via_audit text, p_variacao_id integer, p_tipo_cliente character varying, p_cliente_nome character varying, p_aluno_id integer, p_professor_indicador_id integer, p_desconto numeric, p_parcelas integer, p_observacoes text) TO postgres;
GRANT EXECUTE ON FUNCTION public.registrar_venda_legacy(p_produto_id integer, p_unidade_id uuid, p_quantidade integer, p_forma_pagamento character varying, p_via_audit text, p_variacao_id integer, p_tipo_cliente character varying, p_cliente_nome character varying, p_aluno_id integer, p_professor_indicador_id integer, p_desconto numeric, p_parcelas integer, p_observacoes text) TO service_role;
GRANT EXECUTE ON FUNCTION public.registrar_venda_v2(p_unidade_id uuid, p_itens jsonb, p_forma_pagamento character varying, p_via_audit text, p_tipo_cliente character varying, p_cliente_nome character varying, p_aluno_id integer, p_colaborador_cliente_id integer, p_professor_indicador_id integer, p_desconto numeric, p_desconto_tipo character varying, p_parcelas integer, p_observacoes text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.registrar_venda_v2(p_unidade_id uuid, p_itens jsonb, p_forma_pagamento character varying, p_via_audit text, p_tipo_cliente character varying, p_cliente_nome character varying, p_aluno_id integer, p_colaborador_cliente_id integer, p_professor_indicador_id integer, p_desconto numeric, p_desconto_tipo character varying, p_parcelas integer, p_observacoes text) TO anon;
GRANT EXECUTE ON FUNCTION public.registrar_venda_v2(p_unidade_id uuid, p_itens jsonb, p_forma_pagamento character varying, p_via_audit text, p_tipo_cliente character varying, p_cliente_nome character varying, p_aluno_id integer, p_colaborador_cliente_id integer, p_professor_indicador_id integer, p_desconto numeric, p_desconto_tipo character varying, p_parcelas integer, p_observacoes text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.registrar_venda_v2(p_unidade_id uuid, p_itens jsonb, p_forma_pagamento character varying, p_via_audit text, p_tipo_cliente character varying, p_cliente_nome character varying, p_aluno_id integer, p_colaborador_cliente_id integer, p_professor_indicador_id integer, p_desconto numeric, p_desconto_tipo character varying, p_parcelas integer, p_observacoes text) TO postgres;
GRANT EXECUTE ON FUNCTION public.registrar_venda_v2(p_unidade_id uuid, p_itens jsonb, p_forma_pagamento character varying, p_via_audit text, p_tipo_cliente character varying, p_cliente_nome character varying, p_aluno_id integer, p_colaborador_cliente_id integer, p_professor_indicador_id integer, p_desconto numeric, p_desconto_tipo character varying, p_parcelas integer, p_observacoes text) TO service_role;
GRANT EXECUTE ON FUNCTION public.resetar_teste_mila(p_lead_id integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.resetar_teste_mila(p_lead_id integer) TO anon;
GRANT EXECUTE ON FUNCTION public.resetar_teste_mila(p_lead_id integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.resetar_teste_mila(p_lead_id integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.resetar_teste_mila(p_lead_id integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.restaurar_ocorrencia(p_ocorrencia_id integer, p_usuario_id uuid, p_usuario_nome character varying, p_justificativa text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.restaurar_ocorrencia(p_ocorrencia_id integer, p_usuario_id uuid, p_usuario_nome character varying, p_justificativa text) TO anon;
GRANT EXECUTE ON FUNCTION public.restaurar_ocorrencia(p_ocorrencia_id integer, p_usuario_id uuid, p_usuario_nome character varying, p_justificativa text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.restaurar_ocorrencia(p_ocorrencia_id integer, p_usuario_id uuid, p_usuario_nome character varying, p_justificativa text) TO postgres;
GRANT EXECUTE ON FUNCTION public.restaurar_ocorrencia(p_ocorrencia_id integer, p_usuario_id uuid, p_usuario_nome character varying, p_justificativa text) TO service_role;
GRANT EXECUTE ON FUNCTION public.reverter_ocorrencia(p_ocorrencia_id integer, p_usuario_id uuid, p_usuario_nome character varying, p_justificativa text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.reverter_ocorrencia(p_ocorrencia_id integer, p_usuario_id uuid, p_usuario_nome character varying, p_justificativa text) TO anon;
GRANT EXECUTE ON FUNCTION public.reverter_ocorrencia(p_ocorrencia_id integer, p_usuario_id uuid, p_usuario_nome character varying, p_justificativa text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reverter_ocorrencia(p_ocorrencia_id integer, p_usuario_id uuid, p_usuario_nome character varying, p_justificativa text) TO postgres;
GRANT EXECUTE ON FUNCTION public.reverter_ocorrencia(p_ocorrencia_id integer, p_usuario_id uuid, p_usuario_nome character varying, p_justificativa text) TO service_role;
GRANT EXECUTE ON FUNCTION public.rpc_analise_turmas(p_unidade_id uuid, p_ano integer, p_mes integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_analise_turmas(p_unidade_id uuid, p_ano integer, p_mes integer) TO anon;
GRANT EXECUTE ON FUNCTION public.rpc_analise_turmas(p_unidade_id uuid, p_ano integer, p_mes integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.rpc_analise_turmas(p_unidade_id uuid, p_ano integer, p_mes integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.rpc_analise_turmas(p_unidade_id uuid, p_ano integer, p_mes integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.rpc_marcar_inadimplentes() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_marcar_inadimplentes() TO anon;
GRANT EXECUTE ON FUNCTION public.rpc_marcar_inadimplentes() TO authenticated;
GRANT EXECUTE ON FUNCTION public.rpc_marcar_inadimplentes() TO postgres;
GRANT EXECUTE ON FUNCTION public.rpc_marcar_inadimplentes() TO service_role;
GRANT EXECUTE ON FUNCTION public.salvar_historico_trimestral_fideliza(p_ano integer, p_trimestre integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.salvar_historico_trimestral_fideliza(p_ano integer, p_trimestre integer) TO anon;
GRANT EXECUTE ON FUNCTION public.salvar_historico_trimestral_fideliza(p_ano integer, p_trimestre integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.salvar_historico_trimestral_fideliza(p_ano integer, p_trimestre integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.salvar_historico_trimestral_fideliza(p_ano integer, p_trimestre integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.sincronizar_grade_horaria_alunos() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.sincronizar_grade_horaria_alunos() TO anon;
GRANT EXECUTE ON FUNCTION public.sincronizar_grade_horaria_alunos() TO authenticated;
GRANT EXECUTE ON FUNCTION public.sincronizar_grade_horaria_alunos() TO postgres;
GRANT EXECUTE ON FUNCTION public.sincronizar_grade_horaria_alunos() TO service_role;
GRANT EXECUTE ON FUNCTION public.sol_registrar_divergencia(p_aluno_id integer, p_unidade_id uuid, p_emusys_matricula_id text, p_tipo_divergencia text, p_analise text, p_campo text, p_valor_api jsonb, p_sugestao jsonb, p_severidade text) TO anon;
GRANT EXECUTE ON FUNCTION public.sol_registrar_divergencia(p_aluno_id integer, p_unidade_id uuid, p_emusys_matricula_id text, p_tipo_divergencia text, p_analise text, p_campo text, p_valor_api jsonb, p_sugestao jsonb, p_severidade text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.sol_registrar_divergencia(p_aluno_id integer, p_unidade_id uuid, p_emusys_matricula_id text, p_tipo_divergencia text, p_analise text, p_campo text, p_valor_api jsonb, p_sugestao jsonb, p_severidade text) TO postgres;
GRANT EXECUTE ON FUNCTION public.sol_registrar_divergencia(p_aluno_id integer, p_unidade_id uuid, p_emusys_matricula_id text, p_tipo_divergencia text, p_analise text, p_campo text, p_valor_api jsonb, p_sugestao jsonb, p_severidade text) TO service_role;
GRANT EXECUTE ON FUNCTION public.sol_registrar_divergencia(p_aluno_id integer, p_unidade_id uuid, p_emusys_matricula_id text, p_tipo_divergencia text, p_analise text, p_campo text, p_valor_api jsonb, p_sugestao jsonb, p_severidade text) TO sol_acesso_restrito;
GRANT EXECUTE ON FUNCTION public.toggle_mila_conversa(p_conversa_id uuid, p_pausar boolean, p_operador character varying) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.toggle_mila_conversa(p_conversa_id uuid, p_pausar boolean, p_operador character varying) TO anon;
GRANT EXECUTE ON FUNCTION public.toggle_mila_conversa(p_conversa_id uuid, p_pausar boolean, p_operador character varying) TO authenticated;
GRANT EXECUTE ON FUNCTION public.toggle_mila_conversa(p_conversa_id uuid, p_pausar boolean, p_operador character varying) TO postgres;
GRANT EXECUTE ON FUNCTION public.toggle_mila_conversa(p_conversa_id uuid, p_pausar boolean, p_operador character varying) TO service_role;
GRANT EXECUTE ON FUNCTION public.toggle_relatorio_cron(p_unidade_id uuid, p_ativo boolean) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.toggle_relatorio_cron(p_unidade_id uuid, p_ativo boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.toggle_relatorio_cron(p_unidade_id uuid, p_ativo boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.toggle_relatorio_cron(p_unidade_id uuid, p_ativo boolean) TO postgres;
GRANT EXECUTE ON FUNCTION public.toggle_relatorio_cron(p_unidade_id uuid, p_ativo boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.upsert_lead(p_nome text, p_telefone text, p_email text, p_unidade_id uuid, p_curso text, p_canal text, p_source_id integer, p_source_type text, p_arquivar boolean, p_data_contato date) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.upsert_lead(p_nome text, p_telefone text, p_email text, p_unidade_id uuid, p_curso text, p_canal text, p_source_id integer, p_source_type text, p_arquivar boolean, p_data_contato date) TO anon;
GRANT EXECUTE ON FUNCTION public.upsert_lead(p_nome text, p_telefone text, p_email text, p_unidade_id uuid, p_curso text, p_canal text, p_source_id integer, p_source_type text, p_arquivar boolean, p_data_contato date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.upsert_lead(p_nome text, p_telefone text, p_email text, p_unidade_id uuid, p_curso text, p_canal text, p_source_id integer, p_source_type text, p_arquivar boolean, p_data_contato date) TO postgres;
GRANT EXECUTE ON FUNCTION public.upsert_lead(p_nome text, p_telefone text, p_email text, p_unidade_id uuid, p_curso text, p_canal text, p_source_id integer, p_source_type text, p_arquivar boolean, p_data_contato date) TO service_role;
GRANT EXECUTE ON FUNCTION public.usuario_perfis_lista(p_usuario_id integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.usuario_perfis_lista(p_usuario_id integer) TO anon;
GRANT EXECUTE ON FUNCTION public.usuario_perfis_lista(p_usuario_id integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.usuario_perfis_lista(p_usuario_id integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.usuario_perfis_lista(p_usuario_id integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.usuario_permissoes(p_usuario_id integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.usuario_permissoes(p_usuario_id integer) TO anon;
GRANT EXECUTE ON FUNCTION public.usuario_permissoes(p_usuario_id integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.usuario_permissoes(p_usuario_id integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.usuario_permissoes(p_usuario_id integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.usuario_tem_permissao(p_usuario_id integer, p_codigo_permissao character varying, p_unidade_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.usuario_tem_permissao(p_usuario_id integer, p_codigo_permissao character varying, p_unidade_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.usuario_tem_permissao(p_usuario_id integer, p_codigo_permissao character varying, p_unidade_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.usuario_tem_permissao(p_usuario_id integer, p_codigo_permissao character varying, p_unidade_id uuid) TO postgres;
GRANT EXECUTE ON FUNCTION public.usuario_tem_permissao(p_usuario_id integer, p_codigo_permissao character varying, p_unidade_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.vincular_alunos_checklist(p_checklist_id uuid, p_farmer_id integer, p_tipo_vinculo text, p_filtro_ids integer[]) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.vincular_alunos_checklist(p_checklist_id uuid, p_farmer_id integer, p_tipo_vinculo text, p_filtro_ids integer[]) TO anon;
GRANT EXECUTE ON FUNCTION public.vincular_alunos_checklist(p_checklist_id uuid, p_farmer_id integer, p_tipo_vinculo text, p_filtro_ids integer[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.vincular_alunos_checklist(p_checklist_id uuid, p_farmer_id integer, p_tipo_vinculo text, p_filtro_ids integer[]) TO postgres;
GRANT EXECUTE ON FUNCTION public.vincular_alunos_checklist(p_checklist_id uuid, p_farmer_id integer, p_tipo_vinculo text, p_filtro_ids integer[]) TO service_role;
GRANT EXECUTE ON FUNCTION public.vincular_anamnese_aluno(p_anamnese_id integer, p_aluno_id integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.vincular_anamnese_aluno(p_anamnese_id integer, p_aluno_id integer) TO anon;
GRANT EXECUTE ON FUNCTION public.vincular_anamnese_aluno(p_anamnese_id integer, p_aluno_id integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.vincular_anamnese_aluno(p_anamnese_id integer, p_aluno_id integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.vincular_anamnese_aluno(p_anamnese_id integer, p_aluno_id integer) TO service_role;
