-- Consolida o fechamento pedagogico de junho/2026 e corrige duas regras:
-- 1. carteira historica fechada nao pode mudar com alteracoes posteriores;
-- 2. media/turma usa alunos regulares unicos, nunca ocupacoes inferidas;

CREATE TABLE IF NOT EXISTS public.professor_carteira_mensal_canonica (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  competencia date NOT NULL,
  unidade_id uuid NOT NULL REFERENCES public.unidades(id),
  professor_id integer NOT NULL REFERENCES public.professores(id),
  carteira_alunos integer NOT NULL CHECK (carteira_alunos >= 0),
  fonte text NOT NULL,
  auditado_por text,
  auditado_em timestamptz NOT NULL DEFAULT now(),
  observacoes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT professor_carteira_mensal_competencia_inicio_check
    CHECK (competencia = date_trunc('month', competencia)::date),
  CONSTRAINT professor_carteira_mensal_canonica_unique
    UNIQUE (competencia, unidade_id, professor_id)
);

CREATE INDEX IF NOT EXISTS idx_professor_carteira_mensal_unidade_competencia
  ON public.professor_carteira_mensal_canonica (unidade_id, competencia);

ALTER TABLE public.professor_carteira_mensal_canonica ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.professor_carteira_mensal_canonica
  FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.professor_carteira_mensal_canonica TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.professor_carteira_mensal_canonica_id_seq
  TO service_role;

COMMENT ON TABLE public.professor_carteira_mensal_canonica IS
  'Fechamento imutavel da carteira por professor/unidade/competencia, com proveniencia de auditoria.';
COMMENT ON COLUMN public.professor_carteira_mensal_canonica.carteira_alunos IS
  'Quantidade do relatorio Alunos por Professor do Emusys validada no fechamento da competencia.';

WITH auditados (unidade_nome, professor_nome, carteira_alunos) AS (
  VALUES
    ('Barra', 'Ana Beatriz Paz de Almeida', 2),
    ('Barra', 'Daiana Pacifico da Silva dos Anjos', 24),
    ('Barra', 'Erick Cosme da Silva', 7),
    ('Barra', 'Gabriel Antony Alves de Araujo', 46),
    ('Barra', 'Gabriel Santos Teixeira da Silva', 12),
    ('Barra', 'Isaque Mendes da Silva', 28),
    ('Barra', 'Jeyson Gaia Ramos', 2),
    ('Barra', 'Joel de Salles Gouveia Filho', 2),
    ('Barra', 'Larissa Bheattriz Barbosa Santos', 14),
    ('Barra', 'Leonardo Castro', 19),
    ('Barra', 'Lohana Leopoldo de Araujo', 11),
    ('Barra', 'Lucas Amorim Souza', 6),
    ('Barra', 'Mariana Carneiro Ribeiro de Souza', 5),
    ('Barra', 'Matheus Lana da Silva', 28),
    ('Barra', 'Matheus Reis', 10),
    ('Barra', 'Pedro Sergio Figueiredo da Gloria', 6),
    ('Barra', 'Peterson Biancamano', 10),
    ('Barra', 'Willer Arruda Machado', 4),
    ('Barra', 'Willian De Andrade Da Silva', 27),

    ('Recreio', 'Alexandre de Sa Ritta do Espirito Santo', 20),
    ('Recreio', 'Ana Beatriz Paz de Almeida', 2),
    ('Recreio', 'Caio Tenorio de Araujo', 6),
    ('Recreio', 'Erick Cosme da Silva', 19),
    ('Recreio', 'Isaque Mendes da Silva', 8),
    ('Recreio', 'Israel Rocha da Silva', 15),
    ('Recreio', 'Joel de Salles Gouveia Filho', 13),
    ('Recreio', 'Kaio Felipe Rodrigues Cabral', 6),
    ('Recreio', 'Larissa Bheattriz Barbosa Santos', 30),
    ('Recreio', 'Leticia de Almeida Palmeira', 40),
    ('Recreio', 'Lohana Leopoldo de Araujo', 25),
    ('Recreio', 'Lucas da Silva Guimaraes', 44),
    ('Recreio', 'Marcos Serafim', 4),
    ('Recreio', 'Matheus dos Santos Silva de Oliveira', 12),
    ('Recreio', 'Matheus Felipe Lourenco', 4),
    ('Recreio', 'Matheus Lana da Silva', 3),
    ('Recreio', 'Matheus Reis da Silva Gaspar', 1),
    ('Recreio', 'Rafael Alves Souza (Akeem)', 57),
    ('Recreio', 'Ramon Pina Morais', 40),
    ('Recreio', 'Renan Amorim Guimaraes', 13),
    ('Recreio', 'Valdo Delfino', 9),
    ('Recreio', 'Vicente Pinheiro Neto', 13),
    ('Recreio', 'Willer Arruda Machado', 21),
    ('Recreio', 'Willian De Andrade Da Silva', 17),

    ('Campo Grande', 'Alan Samico do Nascimento', 8),
    ('Campo Grande', 'Alexandre de Sa Ritta do Espirito Santo', 22),
    ('Campo Grande', 'Ana Beatriz Paz de Almeida', 2),
    ('Campo Grande', 'Antonio Marcos Angelo Dantas Filho', 1),
    ('Campo Grande', 'Caio Tenorio de Araujo', 51),
    ('Campo Grande', 'Daiana Pacifico da Silva dos Anjos', 14),
    ('Campo Grande', 'Fabricio Costa de Oliveira', 14),
    ('Campo Grande', 'Gabriel Barbosa Rufino Otavio', 28),
    ('Campo Grande', 'Gabriel Santos Teixeira da Silva', 30),
    ('Campo Grande', 'Israel Rocha da Silva', 14),
    ('Campo Grande', 'Jeyson Gaia Ramos', 7),
    ('Campo Grande', 'Joel de Salles Gouveia Filho', 21),
    ('Campo Grande', 'Jordan Barbosa do Rego', 19),
    ('Campo Grande', 'Kaio Felipe Rodrigues Cabral', 45),
    ('Campo Grande', 'Leonardo Castro', 0),
    ('Campo Grande', 'Leticia de Almeida Palmeira', 9),
    ('Campo Grande', 'Lohana Leopoldo de Araujo', 14),
    ('Campo Grande', 'Lucas Souza dos Santos', 3),
    ('Campo Grande', 'Marcos (Marquinhos) da Silva Saturnino', 19),
    ('Campo Grande', 'Marcos Delfino Serafim', 9),
    ('Campo Grande', 'Matheus dos Santos Silva de Oliveira', 13),
    ('Campo Grande', 'Matheus Felipe Lourenco', 15),
    ('Campo Grande', 'Matheus Sterque Mendes', 9),
    ('Campo Grande', 'Pedro Sergio Figueiredo da Gloria', 40),
    ('Campo Grande', 'Peterson Biancamano', 28),
    ('Campo Grande', 'Ramon Pina Morais', 14),
    ('Campo Grande', 'Renan Amorim Guimaraes', 17),
    ('Campo Grande', 'Rodrigo Pinheiro Gomes', 38),
    ('Campo Grande', 'Valdo Delfino', 28),
    ('Campo Grande', 'Willer Arruda Machado', 8),
    ('Campo Grande', 'Willian Luiz Barros Ribeiro', 17)
),
resolvidos AS (
  SELECT
    u.id AS unidade_id,
    p.id AS professor_id,
    a.carteira_alunos
  FROM auditados a
  JOIN public.unidades u ON u.nome = a.unidade_nome
  JOIN public.professores p
    ON lower(unaccent(p.nome)) = lower(a.professor_nome)
)
INSERT INTO public.professor_carteira_mensal_canonica (
  competencia,
  unidade_id,
  professor_id,
  carteira_alunos,
  fonte,
  auditado_por,
  observacoes
)
SELECT
  DATE '2026-06-01',
  r.unidade_id,
  r.professor_id,
  r.carteira_alunos,
  'coordenacao_emusys',
  'Marcos Quintela e Juliana Baltazar',
  'Levantamento no relatorio Alunos por Professor do Emusys recebido em 14/07/2026.'
FROM resolvidos r
ON CONFLICT (competencia, unidade_id, professor_id) DO NOTHING;

DO $$
DECLARE
  v_total integer;
BEGIN
  SELECT count(*)
    INTO v_total
  FROM public.professor_carteira_mensal_canonica
  WHERE competencia = DATE '2026-06-01'
    AND fonte = 'coordenacao_emusys';

  IF v_total <> 74 THEN
    RAISE EXCEPTION
      'Fechamento de junho incompleto: esperado 74, encontrado %', v_total;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_carteira_professor_periodo_canonica(
  p_ano integer,
  p_mes integer,
  p_unidade_id uuid DEFAULT NULL,
  p_data_inicio date DEFAULT NULL,
  p_data_fim date DEFAULT NULL
)
RETURNS TABLE (
  professor_id integer,
  unidade_id uuid,
  carteira_alunos integer,
  media_alunos_turma numeric,
  total_turmas integer,
  alunos_via_turmas integer,
  turmas_elegiveis_media integer,
  fonte_carteira text
)
LANGUAGE plpgsql
STABLE
SET search_path = public
AS $$
DECLARE
  v_competencia date := make_date(p_ano, p_mes, 1);
  v_inicio date := COALESCE(p_data_inicio, make_date(p_ano, p_mes, 1));
  v_fim date;
  v_periodo_mensal boolean;
BEGIN
  v_fim := COALESCE(p_data_fim, (v_inicio + interval '1 month - 1 day')::date);
  v_periodo_mensal := v_inicio = v_competencia
    AND v_fim = (v_competencia + interval '1 month - 1 day')::date;

  RETURN QUERY
  WITH roster_periodo AS (
    SELECT DISTINCT
      ae.professor_id AS prof_id,
      ae.unidade_id AS uid,
      COALESCE(
        aa.aluno_emusys_id::text,
        NULLIF(a.emusys_student_id, ''),
        NULLIF(aa.aluno_chave, ''),
        CASE WHEN aa.aluno_id IS NOT NULL THEN 'local:' || aa.aluno_id::text END
      ) AS pessoa_chave,
      CASE
        WHEN NULLIF(btrim(ae.turma_nome), '') IS NOT NULL THEN
          'turma:'
          || COALESCE(ae.curso_emusys_id::text, lower(btrim(ae.curso_nome)), 'sem-curso')
          || ':' || lower(btrim(ae.turma_nome))
        ELSE
          'individual:' || COALESCE(
            ae.matricula_disciplina_id::text,
            COALESCE(
              aa.aluno_emusys_id::text,
              NULLIF(a.emusys_student_id, ''),
              NULLIF(aa.aluno_chave, ''),
              CASE WHEN aa.aluno_id IS NOT NULL THEN 'local:' || aa.aluno_id::text END
            )
            || ':' || COALESCE(ae.curso_emusys_id::text, lower(btrim(ae.curso_nome)), 'sem-curso')
            || ':' || extract(isodow FROM ae.data_aula)::text
            || ':' || to_char(
              ae.data_hora_inicio AT TIME ZONE 'America/Sao_Paulo',
              'HH24:MI'
            ),
            'evento:' || ae.id::text
          )
      END AS turma_chave,
      NOT COALESCE(c.is_projeto_banda, false) AS elegivel_media,
      'evento'::text AS fonte
    FROM public.aulas_emusys ae
    JOIN public.aula_alunos_emusys aa ON aa.aula_emusys_id = ae.id
    LEFT JOIN public.alunos a ON a.id = aa.aluno_id
    LEFT JOIN public.curso_emusys_depara d
      ON d.unidade_id = ae.unidade_id
     AND d.emusys_disciplina_id = ae.curso_emusys_id
    LEFT JOIN public.cursos c ON c.id = d.curso_id
    WHERE ae.professor_id IS NOT NULL
      AND ae.data_aula BETWEEN v_inicio AND v_fim
      AND ae.cancelada = false
      AND lower(COALESCE(ae.categoria, 'normal')) = 'normal'
      AND (p_unidade_id IS NULL OR ae.unidade_id = p_unidade_id)
  ),
  presenca_periodo AS (
    SELECT DISTINCT
      ae.professor_id AS prof_id,
      ae.unidade_id AS uid,
      COALESCE(NULLIF(a.emusys_student_id, ''), 'local:' || a.id::text) AS pessoa_chave,
      CASE
        WHEN NULLIF(btrim(ae.turma_nome), '') IS NOT NULL THEN
          'turma:'
          || COALESCE(ae.curso_emusys_id::text, lower(btrim(ae.curso_nome)), 'sem-curso')
          || ':' || lower(btrim(ae.turma_nome))
        ELSE
          'individual:' || COALESCE(
            ae.matricula_disciplina_id::text,
            COALESCE(NULLIF(a.emusys_student_id, ''), 'local:' || a.id::text)
            || ':' || COALESCE(ae.curso_emusys_id::text, lower(btrim(ae.curso_nome)), 'sem-curso')
            || ':' || extract(isodow FROM ae.data_aula)::text
            || ':' || to_char(
              ae.data_hora_inicio AT TIME ZONE 'America/Sao_Paulo',
              'HH24:MI'
            ),
            'evento:' || ae.id::text
          )
      END AS turma_chave,
      NOT COALESCE(c.is_projeto_banda, false) AS elegivel_media,
      'evento'::text AS fonte
    FROM public.aulas_emusys ae
    JOIN public.aluno_presenca ap ON ap.aula_emusys_id = ae.id
    JOIN public.alunos a ON a.id = ap.aluno_id
    LEFT JOIN public.curso_emusys_depara d
      ON d.unidade_id = ae.unidade_id
     AND d.emusys_disciplina_id = ae.curso_emusys_id
    LEFT JOIN public.cursos c ON c.id = d.curso_id
    WHERE ae.professor_id IS NOT NULL
      AND ae.data_aula BETWEEN v_inicio AND v_fim
      AND ae.cancelada = false
      AND lower(COALESCE(ae.categoria, 'normal')) = 'normal'
      AND (p_unidade_id IS NULL OR ae.unidade_id = p_unidade_id)
  ),
  eventos_periodo AS (
    SELECT DISTINCT
      e.prof_id,
      e.uid,
      e.pessoa_chave,
      e.turma_chave,
      e.elegivel_media,
      e.fonte
    FROM (
      SELECT * FROM roster_periodo
      UNION ALL
      SELECT * FROM presenca_periodo
    ) e
    WHERE e.pessoa_chave IS NOT NULL
  ),
  jornada_atual AS (
    SELECT DISTINCT
      j.professor_id AS prof_id,
      j.unidade_id AS uid,
      COALESCE(
        j.emusys_aluno_id::text,
        NULLIF(a.emusys_student_id, ''),
        CASE WHEN j.aluno_id IS NOT NULL THEN 'local:' || j.aluno_id::text END
      ) AS pessoa_chave,
      CASE
        WHEN NULLIF(btrim(j.payload_snapshot #>> '{disciplina,nome_turma}'), '') IS NOT NULL THEN
          'turma:'
          || COALESCE(j.curso_id::text, lower(btrim(j.curso_nome_emusys)), 'sem-curso')
          || ':' || lower(btrim(j.payload_snapshot #>> '{disciplina,nome_turma}'))
        WHEN lower(COALESCE(j.payload_snapshot #>> '{disciplina,tipo}', '')) = 'turma'
          AND j.dia_semana IS NOT NULL
          AND j.horario IS NOT NULL THEN
          'turma:'
          || COALESCE(j.curso_id::text, lower(btrim(j.curso_nome_emusys)), 'sem-curso')
          || ':' || lower(j.dia_semana)
          || ':' || j.horario
        ELSE
          'individual:' || COALESCE(
            j.emusys_matricula_disciplina_id::text,
            j.id::text
          )
      END AS turma_chave,
      NOT COALESCE(c.is_projeto_banda, false) AS elegivel_media,
      'jornada'::text AS fonte
    FROM public.aluno_jornada_matricula_disciplina j
    LEFT JOIN public.alunos a ON a.id = j.aluno_id
    LEFT JOIN public.cursos c ON c.id = j.curso_id
    WHERE current_date BETWEEN v_inicio AND v_fim
      AND j.status_matricula = 'ativa'
      AND j.professor_id IS NOT NULL
      AND (p_unidade_id IS NULL OR j.unidade_id = p_unidade_id)
  ),
  legado_periodo AS (
    SELECT DISTINCT
      a.professor_atual_id AS prof_id,
      a.unidade_id AS uid,
      COALESCE(NULLIF(a.emusys_student_id, ''), 'local:' || a.id::text) AS pessoa_chave,
      CASE
        WHEN a.dia_aula IS NOT NULL AND a.horario_aula IS NOT NULL THEN
          'legado:' || a.curso_id::text
          || ':' || lower(a.dia_aula)
          || ':' || a.horario_aula::text
        ELSE 'legado-individual:' || a.id::text
      END AS turma_chave,
      NOT COALESCE(c.is_projeto_banda, false) AS elegivel_media,
      'legado'::text AS fonte
    FROM public.alunos a
    JOIN public.cursos c ON c.id = a.curso_id
    WHERE a.professor_atual_id IS NOT NULL
      AND COALESCE(a.data_matricula, a.data_inicio_contrato, a.created_at::date) <= v_fim
      AND (a.data_saida IS NULL OR a.data_saida > v_fim)
      AND (
        a.arquivado_em IS NULL
        OR (a.arquivado_em AT TIME ZONE 'America/Sao_Paulo')::date > v_fim
      )
      AND (
        lower(COALESCE(a.status, 'ativo')) IN ('ativo', 'ativa')
        OR a.data_saida > v_fim
      )
      AND (p_unidade_id IS NULL OR a.unidade_id = p_unidade_id)
  ),
  fontes AS (
    SELECT * FROM jornada_atual
    UNION ALL
    SELECT * FROM eventos_periodo
    UNION ALL
    SELECT * FROM legado_periodo
  ),
  fonte_preferida AS (
    SELECT
      f.prof_id,
      f.uid,
      CASE
        WHEN bool_or(f.fonte = 'jornada') THEN 'jornada'
        WHEN bool_or(f.fonte = 'evento') THEN 'evento'
        ELSE 'legado'
      END AS fonte
    FROM fontes f
    WHERE f.pessoa_chave IS NOT NULL
    GROUP BY f.prof_id, f.uid
  ),
  base_carteira AS (
    SELECT DISTINCT
      f.prof_id,
      f.uid,
      f.pessoa_chave,
      f.turma_chave,
      f.elegivel_media,
      f.fonte
    FROM fontes f
    JOIN fonte_preferida fp
      ON fp.prof_id = f.prof_id
     AND fp.uid = f.uid
     AND fp.fonte = f.fonte
    WHERE f.pessoa_chave IS NOT NULL
  ),
  carteira AS (
    SELECT
      b.prof_id,
      b.uid,
      COUNT(DISTINCT b.pessoa_chave)::integer AS carteira_alunos,
      min(b.fonte)::text AS fonte_carteira
    FROM base_carteira b
    GROUP BY b.prof_id, b.uid
  ),
  turmas_calc AS (
    SELECT
      b.prof_id,
      b.uid,
      COUNT(DISTINCT b.turma_chave)::integer AS total_turmas,
      COUNT(DISTINCT b.pessoa_chave) FILTER (
        WHERE b.elegivel_media
      )::integer AS alunos_via_turmas,
      COUNT(DISTINCT b.turma_chave) FILTER (
        WHERE b.elegivel_media
      )::integer AS turmas_elegiveis_media,
      CASE
        WHEN COUNT(DISTINCT b.turma_chave) FILTER (WHERE b.elegivel_media) > 0 THEN ROUND(
          COUNT(DISTINCT b.pessoa_chave) FILTER (WHERE b.elegivel_media)::numeric
          / COUNT(DISTINCT b.turma_chave) FILTER (WHERE b.elegivel_media),
          2
        )
        ELSE 0
      END AS media_alunos_turma
    FROM base_carteira b
    GROUP BY b.prof_id, b.uid
  ),
  snapshot AS (
    SELECT
      s.professor_id AS prof_id,
      s.unidade_id AS uid,
      s.carteira_alunos
    FROM public.professor_carteira_mensal_canonica s
    WHERE v_periodo_mensal
      AND s.competencia = v_competencia
      AND (p_unidade_id IS NULL OR s.unidade_id = p_unidade_id)
  )
  SELECT
    COALESCE(s.prof_id, c.prof_id),
    COALESCE(s.uid, c.uid),
    COALESCE(s.carteira_alunos, c.carteira_alunos, 0),
    COALESCE(tc.media_alunos_turma, 0)::numeric(10,2),
    COALESCE(tc.total_turmas, 0),
    COALESCE(tc.alunos_via_turmas, 0),
    COALESCE(tc.turmas_elegiveis_media, 0),
    CASE
      WHEN s.prof_id IS NOT NULL THEN 'snapshot_auditado'
      ELSE COALESCE(c.fonte_carteira, 'sem_base')
    END::text AS fonte_carteira
  FROM carteira c
  FULL JOIN snapshot s
    ON s.prof_id = c.prof_id
   AND s.uid = c.uid
  LEFT JOIN turmas_calc tc
    ON tc.prof_id = COALESCE(s.prof_id, c.prof_id)
   AND tc.uid = COALESCE(s.uid, c.uid)
  ORDER BY COALESCE(s.prof_id, c.prof_id), COALESCE(s.uid, c.uid);
END;
$$;

REVOKE ALL ON FUNCTION public.get_carteira_professor_periodo_canonica(
  integer, integer, uuid, date, date
) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_carteira_professor_periodo_canonica(
  integer, integer, uuid, date, date
) TO service_role;

COMMENT ON FUNCTION public.get_carteira_professor_periodo_canonica(
  integer, integer, uuid, date, date
) IS 'Carteira por competencia: snapshot auditado no mes fechado; jornada/eventos no aberto. Media = alunos regulares unicos / turmas regulares.';

-- Conversao individual do professor: somente a matricula ligada diretamente
-- a uma experimental realizada por ele. Diferencas da conciliacao da unidade
-- permanecem na qualidade de dados e nunca sao distribuidas entre professores.
CREATE OR REPLACE FUNCTION public.get_experimentais_professor_canonicos_v1(
  p_unidade_id uuid,
  p_ano integer,
  p_mes_inicio integer,
  p_mes_fim integer DEFAULT NULL
)
RETURNS TABLE (
  professor_id integer,
  professor_nome text,
  unidade_id uuid,
  unidade_nome text,
  realizadas_emusys integer,
  faltas_emusys integer,
  canceladas_emusys integer,
  matriculas_pos_exp integer,
  taxa_exp_mat numeric
)
LANGUAGE sql
STABLE
SET search_path = public, pg_temp
AS $$
WITH periodo AS (
  SELECT
    make_date(p_ano, p_mes_inicio, 1) AS inicio,
    (
      make_date(p_ano, COALESCE(NULLIF(p_mes_fim, 0), p_mes_inicio), 1)
      + interval '1 month'
    ) AS fim_exclusivo
),
unidades_alvo AS (
  SELECT u.id AS unidade_id, u.nome AS unidade_nome
  FROM public.unidades u
  WHERE u.ativo = true
    AND (p_unidade_id IS NULL OR u.id = p_unidade_id)
),
raw_eventos AS (
  SELECT
    r.id,
    r.professor_id,
    COALESCE(max(p.nome), max(NULLIF(r.professor_nome, '')), 'Sem professor') AS professor_nome,
    r.unidade_id,
    ua.unidade_nome,
    r.situacao_operacional,
    r.data_aula,
    a.id AS aluno_matriculado_id,
    row_number() OVER (
      PARTITION BY r.unidade_id, a.id
      ORDER BY r.data_aula DESC NULLS LAST, r.id DESC
    ) AS ordem_conversao_aluno
  FROM public.emusys_experimentais_raw r
  JOIN periodo pr ON true
  JOIN unidades_alvo ua ON ua.unidade_id = r.unidade_id
  LEFT JOIN public.professores p ON p.id = r.professor_id
  LEFT JOIN public.alunos a
    ON a.id = r.aluno_id
   AND a.unidade_id = r.unidade_id
   AND r.situacao_operacional IN ('presente', 'matriculado')
   AND lower(COALESCE(a.status, '')) <> 'excluido'
   AND a.data_matricula >= pr.inicio::date
   AND a.data_matricula < pr.fim_exclusivo::date
   AND COALESCE(a.valor_passaporte, 0) > 0
  WHERE r.data_aula >= pr.inicio::date
    AND r.data_aula < pr.fim_exclusivo::date
    AND r.professor_id IS NOT NULL
  GROUP BY
    r.id,
    r.professor_id,
    r.unidade_id,
    ua.unidade_nome,
    r.situacao_operacional,
    r.data_aula,
    a.id
),
raw_por_professor AS (
  SELECT
    r.professor_id,
    COALESCE(max(r.professor_nome), 'Sem professor') AS professor_nome,
    r.unidade_id,
    r.unidade_nome,
    count(*) FILTER (
      WHERE r.situacao_operacional IN ('presente', 'matriculado')
    )::integer AS realizadas_emusys,
    count(*) FILTER (
      WHERE r.situacao_operacional = 'faltou'
    )::integer AS faltas_emusys,
    count(*) FILTER (
      WHERE r.situacao_operacional = 'cancelada'
    )::integer AS canceladas_emusys,
    count(*) FILTER (
      WHERE r.aluno_matriculado_id IS NOT NULL
        AND r.ordem_conversao_aluno = 1
    )::integer AS raw_matriculas_pos_exp
  FROM raw_eventos r
  GROUP BY r.professor_id, r.unidade_id, r.unidade_nome
)
SELECT
  r.professor_id,
  r.professor_nome,
  r.unidade_id,
  r.unidade_nome,
  r.realizadas_emusys,
  r.faltas_emusys,
  r.canceladas_emusys,
  r.raw_matriculas_pos_exp AS matriculas_pos_exp,
  CASE
    WHEN r.realizadas_emusys > 0 THEN round(
      r.raw_matriculas_pos_exp::numeric / r.realizadas_emusys::numeric * 100,
      1
    )
    ELSE 0
  END AS taxa_exp_mat
FROM raw_por_professor r
ORDER BY r.realizadas_emusys DESC, r.raw_matriculas_pos_exp DESC, r.professor_nome;
$$;

REVOKE ALL ON FUNCTION public.get_experimentais_professor_canonicos_v1(
  uuid, integer, integer, integer
) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_experimentais_professor_canonicos_v1(
  uuid, integer, integer, integer
) TO authenticated, service_role;

COMMENT ON FUNCTION public.get_experimentais_professor_canonicos_v1(
  uuid, integer, integer, integer
) IS 'Metricas por professor: experimental realizada e conversao diretamente vinculada no bruto Emusys. Nunca distribui diferenca da unidade.';
