begin;

alter table public.aluno_jornada_matricula_disciplina
  add column if not exists emusys_disciplina_id_origem bigint,
  add column if not exists curso_id_origem integer,
  add column if not exists curso_nome_emusys_origem text,
  add column if not exists curso_resolucao_fonte text not null default 'matriculas_api',
  add column if not exists curso_resolucao_confianca text,
  add column if not exists curso_resolvido_em timestamptz,
  add column if not exists curso_resolucao_evidencias jsonb not null default '{}'::jsonb;

create table if not exists public.jornada_curso_resolucao_log (
  id bigint generated by default as identity primary key,
  jornada_id uuid not null references public.aluno_jornada_matricula_disciplina(id) on delete cascade,
  unidade_id uuid not null references public.unidades(id),
  emusys_matricula_disciplina_id bigint not null,
  emusys_disciplina_id_anterior bigint,
  emusys_disciplina_id_novo bigint,
  curso_id_anterior integer references public.cursos(id),
  curso_id_novo integer references public.cursos(id),
  fonte text not null,
  confianca text not null,
  evidencias jsonb not null default '{}'::jsonb,
  criado_em timestamptz not null default now()
);

create index if not exists idx_jornada_curso_resolucao_log_jornada
  on public.jornada_curso_resolucao_log (jornada_id, criado_em desc);

alter table public.jornada_curso_resolucao_log enable row level security;
revoke all on table public.jornada_curso_resolucao_log from public, anon, authenticated;
grant select, insert on table public.jornada_curso_resolucao_log to service_role;

create or replace function public.fn_resolver_jornada_curso_grade_atual_v1(
  p_unidade_id uuid,
  p_matricula_disciplina_id bigint
)
returns table (
  emusys_disciplina_id bigint,
  curso_id integer,
  curso_nome_grade text,
  modalidade text,
  aulas_evidencia integer,
  aulas_futuras integer,
  aulas_regulares integer,
  data_ultima_aula date
)
language sql
stable
security definer
set search_path = public, pg_temp
as $function$
  with candidatos as (
    select
      a.curso_emusys_id::bigint as emusys_disciplina_id,
      d.curso_id,
      coalesce(max(nullif(btrim(a.curso_nome), '')), max(c.nome)) as curso_nome_grade,
      cat.modalidade,
      count(*)::integer as aulas_evidencia,
      count(*) filter (where a.data_aula >= current_date)::integer as aulas_futuras,
      count(*) filter (where not coalesce(a.reagendada, false))::integer as aulas_regulares,
      max(a.data_aula) as data_ultima_aula
    from public.aulas_emusys a
    join public.curso_emusys_depara d
      on d.unidade_id = a.unidade_id
     and d.emusys_disciplina_id = a.curso_emusys_id
     and d.status_mapeamento = 'mapeado'
    join public.emusys_disciplinas_catalogo cat
      on cat.unidade_id = a.unidade_id
     and cat.emusys_disciplina_id = a.curso_emusys_id
    left join public.cursos c on c.id = d.curso_id
    where a.unidade_id = p_unidade_id
      and a.matricula_disciplina_id = p_matricula_disciplina_id
      and a.data_aula between current_date - 14 and current_date + 60
      and lower(coalesce(a.categoria, 'normal')) = 'normal'
      and not coalesce(a.cancelada, false)
      and a.curso_emusys_id is not null
      and cat.modalidade in ('individual', 'turma')
    group by a.curso_emusys_id, d.curso_id, cat.modalidade
    having count(*) filter (
      where not coalesce(a.reagendada, false)
    ) >= 2
      or count(*) filter (where a.data_aula >= current_date) >= 2
  )
  select
    c.emusys_disciplina_id,
    c.curso_id,
    c.curso_nome_grade,
    c.modalidade,
    c.aulas_evidencia,
    c.aulas_futuras,
    c.aulas_regulares,
    c.data_ultima_aula
  from candidatos c
  order by
    c.aulas_futuras desc,
    c.data_ultima_aula desc,
    c.aulas_regulares desc,
    c.emusys_disciplina_id
  limit 1;
$function$;

create or replace function public.fn_aplicar_jornada_curso_grade_atual_v1()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  v_grade record;
  v_disciplina_api bigint;
  v_curso_api integer;
  v_nome_api text;
  v_evidencias jsonb;
  v_deve_logar boolean := false;
begin
  begin
    v_disciplina_api := nullif(
      new.payload_snapshot -> 'disciplina' ->> 'disciplina_id',
      ''
    )::bigint;
  exception when invalid_text_representation then
    v_disciplina_api := null;
  end;

  v_disciplina_api := coalesce(v_disciplina_api, new.emusys_disciplina_id);
  v_curso_api := new.curso_id;
  v_nome_api := coalesce(
    nullif(btrim(new.payload_snapshot -> 'disciplina' ->> 'nome'), ''),
    new.curso_nome_emusys
  );

  new.emusys_disciplina_id_origem := v_disciplina_api;
  new.curso_id_origem := v_curso_api;
  new.curso_nome_emusys_origem := v_nome_api;

  if new.status_matricula = 'ativa'
     and new.emusys_matricula_disciplina_id is not null then
    select * into v_grade
    from public.fn_resolver_jornada_curso_grade_atual_v1(
      new.unidade_id,
      new.emusys_matricula_disciplina_id
    );
  end if;

  if found then
    v_evidencias := jsonb_build_object(
      'regra', 'grade_recorrente_v1',
      'janela_inicio', current_date - 14,
      'janela_fim', current_date + 60,
      'aulas_evidencia', v_grade.aulas_evidencia,
      'aulas_futuras', v_grade.aulas_futuras,
      'aulas_regulares', v_grade.aulas_regulares,
      'data_ultima_aula', v_grade.data_ultima_aula,
      'modalidade', v_grade.modalidade,
      'disciplina_api_id', v_disciplina_api,
      'curso_api_id', v_curso_api,
      'curso_api_nome', v_nome_api,
      'disciplina_grade_id', v_grade.emusys_disciplina_id,
      'curso_grade_id', v_grade.curso_id,
      'curso_grade_nome', v_grade.curso_nome_grade
    );

    if tg_op = 'UPDATE' then
      v_deve_logar := old.curso_id is distinct from v_grade.curso_id
        or old.emusys_disciplina_id is distinct from v_grade.emusys_disciplina_id;
    else
      v_deve_logar := false;
    end if;

    new.emusys_disciplina_id := v_grade.emusys_disciplina_id;
    new.curso_id := v_grade.curso_id;
    new.curso_nome_emusys := v_grade.curso_nome_grade;
    new.curso_resolucao_fonte := 'grade_recorrente_v1';
    new.curso_resolucao_confianca := 'alta';
    new.curso_resolvido_em := now();
    new.curso_resolucao_evidencias := v_evidencias;
    new.payload_snapshot := jsonb_set(
      coalesce(new.payload_snapshot, '{}'::jsonb),
      '{resolucao_curso}',
      v_evidencias,
      true
    );

    if v_deve_logar then
      insert into public.jornada_curso_resolucao_log (
        jornada_id,
        unidade_id,
        emusys_matricula_disciplina_id,
        emusys_disciplina_id_anterior,
        emusys_disciplina_id_novo,
        curso_id_anterior,
        curso_id_novo,
        fonte,
        confianca,
        evidencias
      ) values (
        new.id,
        new.unidade_id,
        new.emusys_matricula_disciplina_id,
        case when tg_op = 'UPDATE' then old.emusys_disciplina_id else v_disciplina_api end,
        v_grade.emusys_disciplina_id,
        case when tg_op = 'UPDATE' then old.curso_id else v_curso_api end,
        v_grade.curso_id,
        'grade_recorrente_v1',
        'alta',
        v_evidencias
      );
    end if;
  elsif tg_op = 'UPDATE'
    and old.curso_resolucao_fonte = 'grade_recorrente_v1'
    and v_disciplina_api is not distinct from old.emusys_disciplina_id_origem then
    new.emusys_disciplina_id := old.emusys_disciplina_id;
    new.curso_id := old.curso_id;
    new.curso_nome_emusys := old.curso_nome_emusys;
    new.curso_resolucao_fonte := old.curso_resolucao_fonte;
    new.curso_resolucao_confianca := old.curso_resolucao_confianca;
    new.curso_resolvido_em := old.curso_resolvido_em;
    new.curso_resolucao_evidencias := old.curso_resolucao_evidencias;
    new.payload_snapshot := jsonb_set(
      coalesce(new.payload_snapshot, '{}'::jsonb),
      '{resolucao_curso}',
      coalesce(old.curso_resolucao_evidencias, '{}'::jsonb),
      true
    );
  else
    new.curso_resolucao_fonte := 'matriculas_api';
    new.curso_resolucao_confianca := null;
    new.curso_resolvido_em := null;
    new.curso_resolucao_evidencias := '{}'::jsonb;
    new.payload_snapshot := coalesce(new.payload_snapshot, '{}'::jsonb)
      - 'resolucao_curso';
  end if;

  return new;
end;
$function$;

drop trigger if exists trg_resolver_jornada_curso_grade_atual_v1
  on public.aluno_jornada_matricula_disciplina;
create trigger trg_resolver_jornada_curso_grade_atual_v1
before insert or update on public.aluno_jornada_matricula_disciplina
for each row execute function public.fn_aplicar_jornada_curso_grade_atual_v1();

create or replace function public.backfill_jornada_curso_grade_atual_v1(
  p_limite integer default 100
)
returns jsonb
language plpgsql
volatile
security definer
set search_path = public, pg_temp
as $function$
declare
  v_limite integer := greatest(1, least(coalesce(p_limite, 100), 500));
  v_processados integer := 0;
  v_ids jsonb := '[]'::jsonb;
  v_restantes integer := 0;
begin
  with alvos as (
    select j.id
    from public.aluno_jornada_matricula_disciplina j
    cross join lateral public.fn_resolver_jornada_curso_grade_atual_v1(
      j.unidade_id,
      j.emusys_matricula_disciplina_id
    ) r
    where j.status_matricula = 'ativa'
      and (
        j.curso_id is distinct from r.curso_id
        or j.emusys_disciplina_id is distinct from r.emusys_disciplina_id
      )
    order by j.id::text
    limit v_limite
    for update of j skip locked
  ), atualizados as (
    update public.aluno_jornada_matricula_disciplina j
       set fonte_ultima_atualizacao = 'backfill:grade_recorrente_v1',
           updated_at = now()
      from alvos a
     where j.id = a.id
    returning j.id
  )
  select count(*)::integer, coalesce(jsonb_agg(id order by id::text), '[]'::jsonb)
    into v_processados, v_ids
  from atualizados;

  select count(*)::integer into v_restantes
  from public.aluno_jornada_matricula_disciplina j
  cross join lateral public.fn_resolver_jornada_curso_grade_atual_v1(
    j.unidade_id,
    j.emusys_matricula_disciplina_id
  ) r
  where j.status_matricula = 'ativa'
    and (
      j.curso_id is distinct from r.curso_id
      or j.emusys_disciplina_id is distinct from r.emusys_disciplina_id
    );

  return jsonb_build_object(
    'processados', v_processados,
    'restantes', v_restantes,
    'jornada_ids', v_ids,
    'regra', 'grade_recorrente_v1'
  );
end;
$function$;

revoke all on function public.fn_resolver_jornada_curso_grade_atual_v1(uuid, bigint)
  from public, anon, authenticated;
revoke all on function public.fn_aplicar_jornada_curso_grade_atual_v1()
  from public, anon, authenticated;
revoke all on function public.backfill_jornada_curso_grade_atual_v1(integer)
  from public, anon, authenticated;

grant execute on function public.fn_resolver_jornada_curso_grade_atual_v1(uuid, bigint)
  to service_role;
grant execute on function public.backfill_jornada_curso_grade_atual_v1(integer)
  to service_role;

comment on function public.fn_resolver_jornada_curso_grade_atual_v1(uuid, bigint)
is 'Resolve o curso atual da jornada por grade recorrente forte, preservando o payload bruto do endpoint de matriculas.';
comment on function public.backfill_jornada_curso_grade_atual_v1(integer)
is 'Reconcilia em lote jornadas ativas cujo curso do endpoint de matriculas diverge da grade recorrente atual.';
comment on table public.jornada_curso_resolucao_log
is 'Trilha append-only das trocas de curso canonico resolvidas pela grade recorrente do Emusys.';

commit;
