begin;

-- Fontes pedagogicas independentes:
--   anotacoes       = espelho exclusivo do Emusys
--   anotacoes_fabio = registro exclusivo do Fabio via registrar_aula_fabio
alter table public.aulas_emusys
  add column if not exists anotacoes_fabio text;

comment on column public.aulas_emusys.anotacoes is
  'Espelho da anotacao recebida do Emusys. Escrita somente pelos syncs Emusys.';

comment on column public.aulas_emusys.anotacoes_fabio is
  'Registro pedagogico interno do Fabio. Nao pode ser escrito ou limpo pelos syncs Emusys.';

create table if not exists public.aula_registros_fabio_log (
  id bigint generated by default as identity primary key,
  aula_id integer not null,
  professor_id integer,
  texto_anterior text,
  texto_novo text,
  origem text,
  modo text,
  criado_em timestamptz not null default now()
);

alter table public.aula_registros_fabio_log enable row level security;
revoke all on table public.aula_registros_fabio_log from public, anon;
grant all on table public.aula_registros_fabio_log to service_role;

create table if not exists public.fabio_protecao_log (
  id bigserial primary key,
  aula_id integer not null,
  motivo text not null,
  tamanho_preservado integer,
  criado_em timestamptz not null default now()
);

alter table public.fabio_protecao_log enable row level security;
revoke all on table public.fabio_protecao_log from public, anon, authenticated;
grant all on table public.fabio_protecao_log to service_role;

comment on table public.fabio_protecao_log is
  'Auditoria de updates que tentaram esvaziar aulas_emusys.anotacoes_fabio e foram neutralizados.';

create or replace function public.fn_proteger_anotacoes_fabio()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if coalesce(btrim(old.anotacoes_fabio), '') <> ''
     and coalesce(btrim(new.anotacoes_fabio), '') = '' then
    new.anotacoes_fabio := old.anotacoes_fabio;

    begin
      insert into public.fabio_protecao_log (
        aula_id,
        motivo,
        tamanho_preservado
      ) values (
        new.id,
        'update tentou apagar anotacoes_fabio; valor preservado',
        length(old.anotacoes_fabio)
      );
    exception when others then
      null; -- A auditoria nunca pode derrubar o update principal.
    end;
  end if;

  return new;
end;
$$;

revoke all on function public.fn_proteger_anotacoes_fabio() from public, anon, authenticated;

drop trigger if exists trg_proteger_anotacoes_fabio on public.aulas_emusys;
create trigger trg_proteger_anotacoes_fabio
before update on public.aulas_emusys
for each row
execute function public.fn_proteger_anotacoes_fabio();

create or replace function public.registrar_aula_fabio(
  p_aula_id integer,
  p_texto text,
  p_origem text default 'audio',
  p_professor_id integer default null,
  p_modo text default 'novo'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_texto_anterior text;
  v_texto_novo text;
begin
  if p_texto is null or btrim(p_texto) = '' then
    raise exception 'Texto do registro nao pode ser vazio';
  end if;

  if p_origem not in ('audio', 'texto') then
    raise exception 'Origem invalida: % (use audio ou texto)', p_origem;
  end if;

  if p_modo not in ('novo', 'substituir', 'complementar') then
    raise exception 'Modo invalido: % (use novo, substituir ou complementar)', p_modo;
  end if;

  select ae.anotacoes_fabio
  into v_texto_anterior
  from public.aulas_emusys ae
  where ae.id = p_aula_id;

  if not found then
    raise exception 'Aula % nao encontrada', p_aula_id;
  end if;

  if v_texto_anterior is not distinct from p_texto then
    return jsonb_build_object(
      'status', 'sem_mudanca',
      'aula_id', p_aula_id,
      'mensagem', 'Texto identico ao ja registrado; nada gravado'
    );
  end if;

  if p_modo = 'complementar'
     and nullif(btrim(coalesce(v_texto_anterior, '')), '') is not null then
    v_texto_novo := v_texto_anterior || E'\n\n--- (complemento) ---\n\n' || p_texto;
  else
    v_texto_novo := p_texto;
  end if;

  update public.aulas_emusys
  set anotacoes_fabio = v_texto_novo
  where id = p_aula_id;

  insert into public.aula_registros_fabio_log (
    aula_id,
    professor_id,
    texto_anterior,
    texto_novo,
    origem,
    modo
  ) values (
    p_aula_id,
    p_professor_id,
    v_texto_anterior,
    v_texto_novo,
    p_origem,
    p_modo
  );

  return jsonb_build_object(
    'status', 'gravado',
    'aula_id', p_aula_id,
    'modo', p_modo,
    'origem', p_origem,
    'tinha_anterior', nullif(btrim(coalesce(v_texto_anterior, '')), '') is not null
  );
end;
$$;

revoke all on function public.registrar_aula_fabio(integer, text, text, integer, text)
  from public, anon;
grant execute on function public.registrar_aula_fabio(integer, text, text, integer, text)
  to authenticated, service_role;

do $$
begin
  if exists (select 1 from pg_roles where rolname = 'fabio_agent') then
    execute 'grant execute on function public.registrar_aula_fabio(integer, text, text, integer, text) to fabio_agent';
    execute 'grant select on table public.aula_registros_fabio_log to fabio_agent';
    execute 'grant select on table public.fabio_protecao_log to fabio_agent';
  end if;
end;
$$;

comment on function public.registrar_aula_fabio(integer, text, text, integer, text) is
  'Unica porta canonica para escrita de aulas_emusys.anotacoes_fabio; preserva anotacoes do Emusys.';

commit;
