-- LA Teacher MVP: roster, first-write-wins, administrative attendance and teacher time.
-- Additive migration: the legacy aluno_presenca.status remains available to current reports.

alter table public.aluno_presenca
  add column if not exists status_presenca text;

update public.aluno_presenca
set status_presenca = case status
  when 'presente' then 'presente'
  when 'ausente' then 'falta'
  else null
end
where status_presenca is null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'aluno_presenca_status_presenca_check'
      and conrelid = 'public.aluno_presenca'::regclass
  ) then
    alter table public.aluno_presenca
      add constraint aluno_presenca_status_presenca_check
      check (status_presenca is null or status_presenca in ('presente', 'falta'));
  end if;
end $$;

alter table public.aluno_presenca
  drop constraint if exists aluno_presenca_respondido_por_check;

alter table public.aluno_presenca
  add constraint aluno_presenca_respondido_por_check
  check (respondido_por is null or respondido_por in (
    'professor_whatsapp',
    'professor_la_teacher',
    'manual',
    'sistema',
    'emusys'
  ));

create index if not exists idx_aluno_presenca_status_canonico
  on public.aluno_presenca (status_presenca, data_aula);

create table if not exists public.aula_alunos_emusys (
  id bigint generated by default as identity primary key,
  aula_emusys_id integer not null references public.aulas_emusys(id) on delete cascade,
  unidade_id uuid not null references public.unidades(id),
  aluno_chave text not null,
  aluno_emusys_id bigint,
  aluno_id integer references public.alunos(id) on delete set null,
  aluno_nome text not null,
  aluno_nome_normalizado text not null,
  sincronizado_em timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint aula_alunos_emusys_aula_chave_uq unique (aula_emusys_id, aluno_chave)
);

create index if not exists idx_aula_alunos_emusys_aluno
  on public.aula_alunos_emusys (aluno_id, aula_emusys_id)
  where aluno_id is not null;

create table if not exists public.aluno_presenca_administrativo (
  id uuid primary key default gen_random_uuid(),
  aluno_id integer not null references public.alunos(id) on delete cascade,
  aula_emusys_id integer not null references public.aulas_emusys(id) on delete cascade,
  unidade_id uuid not null references public.unidades(id),
  justificada boolean not null default false,
  fonte text not null default 'emusys' check (fonte in ('emusys', 'manual_coordenacao')),
  sincronizado_em timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint aluno_presenca_administrativo_aluno_aula_uq unique (aluno_id, aula_emusys_id)
);

create table if not exists public.professor_ponto_confirmacoes (
  id uuid primary key default gen_random_uuid(),
  professor_id integer not null references public.professores(id),
  aula_emusys_id integer not null references public.aulas_emusys(id) on delete cascade,
  unidade_id uuid not null references public.unidades(id),
  data_aula date not null,
  estava_presente boolean not null,
  origem text not null default 'fabio' check (origem in ('fabio', 'coordenacao')),
  respondido_em timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint professor_ponto_confirmacoes_prof_aula_uq unique (professor_id, aula_emusys_id)
);

create table if not exists public.aluno_presenca_retificacoes (
  id uuid primary key default gen_random_uuid(),
  aluno_presenca_id uuid not null references public.aluno_presenca(id),
  unidade_id uuid not null references public.unidades(id),
  status_anterior text,
  status_novo text not null check (status_novo in ('presente', 'falta')),
  respondido_por_anterior text,
  respondido_em_anterior timestamptz,
  motivo text not null check (length(btrim(motivo)) >= 3),
  autor_usuario_id integer not null references public.usuarios(id),
  autor_auth_user_id uuid not null,
  created_at timestamptz not null default now()
);

alter table public.aula_alunos_emusys enable row level security;
alter table public.aluno_presenca_administrativo enable row level security;
alter table public.professor_ponto_confirmacoes enable row level security;
alter table public.aluno_presenca_retificacoes enable row level security;

revoke all on table public.aula_alunos_emusys from anon, authenticated;
revoke all on table public.aluno_presenca_administrativo from anon, authenticated;
revoke all on table public.professor_ponto_confirmacoes from anon, authenticated;
revoke all on table public.aluno_presenca_retificacoes from anon, authenticated;

create or replace function public.fn_professor_do_usuario()
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select p.id
  from public.professores p
  join public.usuarios u on u.id = p.usuario_id
  where u.auth_user_id = auth.uid()
    and coalesce(u.ativo, true)
    and coalesce(p.ativo, true)
  limit 1;
$$;

revoke all on function public.fn_professor_do_usuario() from public, anon;
grant execute on function public.fn_professor_do_usuario() to authenticated, service_role;

-- Existing LA Report screens keep scoped read access. All writes move behind service role or RPCs.
drop policy if exists "Authenticated users can manage attendance" on public.aluno_presenca;
drop policy if exists "Public can update attendance via token" on public.aluno_presenca;
drop policy if exists aluno_presenca_leitura_escopada on public.aluno_presenca;

create policy aluno_presenca_leitura_escopada
  on public.aluno_presenca
  for select
  to authenticated
  using (
    public.is_admin()
    or unidade_id = public.get_user_unidade_id()
    or professor_id = public.fn_professor_do_usuario()
  );

revoke insert, update, delete on table public.aluno_presenca from anon, authenticated;
grant select on table public.aluno_presenca to authenticated;

create or replace function public.app_minha_agenda_sessao(p_data date default current_date)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_professor_id integer := public.fn_professor_do_usuario();
begin
  if v_professor_id is null then
    return jsonb_build_object('erro', 'sem_professor_vinculado');
  end if;

  return coalesce((
    select jsonb_agg(
      jsonb_build_object(
        'aula_id_ancora', ae.id,
        'hora', to_char(ae.data_hora_inicio at time zone 'America/Sao_Paulo', 'HH24:MI'),
        'hora_fim', to_char(ae.data_hora_fim at time zone 'America/Sao_Paulo', 'HH24:MI'),
        'data_hora_inicio', ae.data_hora_inicio,
        'data_hora_fim', ae.data_hora_fim,
        'curso', ae.curso_nome,
        'turma_nome', ae.turma_nome,
        'tipo', ae.tipo,
        'n_alunos', coalesce(roster.n_alunos, 0),
        'n_registradas', coalesce(roster.n_registradas, 0),
        'roster_incompleto', coalesce(roster.n_sem_vinculo, 0) > 0,
        'alunos', coalesce(roster.alunos, '[]'::jsonb)
      )
      order by ae.data_hora_inicio, ae.id
    )
    from public.aulas_emusys ae
    left join lateral (
      select
        count(*) as n_alunos,
        count(ap.id) as n_registradas,
        count(*) filter (where r.aluno_id is null) as n_sem_vinculo,
        jsonb_agg(
          jsonb_build_object(
            'aluno_id', r.aluno_id,
            'nome', r.aluno_nome,
            'presenca', coalesce(
              ap.status_presenca,
              case ap.status when 'presente' then 'presente' when 'ausente' then 'falta' end,
              'a_confirmar'
            ),
            'tem_registro', ap.id is not null,
            'justificada', coalesce(adm.justificada, false)
          )
          order by r.aluno_nome
        ) as alunos
      from public.aula_alunos_emusys r
      left join public.aluno_presenca ap
        on ap.aula_emusys_id = r.aula_emusys_id
       and ap.aluno_id = r.aluno_id
      left join public.aluno_presenca_administrativo adm
        on adm.aula_emusys_id = r.aula_emusys_id
       and adm.aluno_id = r.aluno_id
      where r.aula_emusys_id = ae.id
    ) roster on true
    where ae.professor_id = v_professor_id
      and ae.data_aula = p_data
      and ae.cancelada = false
  ), '[]'::jsonb);
end;
$$;

revoke all on function public.app_minha_agenda_sessao(date) from public, anon;
grant execute on function public.app_minha_agenda_sessao(date) to authenticated;

create or replace function public.app_registrar_presencas_aula(
  p_aula_emusys_id integer,
  p_alunos_ausentes integer[] default '{}'::integer[]
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_professor_id integer := public.fn_professor_do_usuario();
  v_aula public.aulas_emusys%rowtype;
  v_roster_total integer;
  v_ja_existentes integer;
  v_inseridos integer;
begin
  if v_professor_id is null then
    raise exception 'sem_professor_vinculado' using errcode = '42501';
  end if;

  select * into v_aula
  from public.aulas_emusys
  where id = p_aula_emusys_id;

  if not found or v_aula.professor_id is distinct from v_professor_id then
    raise exception 'aula_nao_pertence_ao_professor' using errcode = '42501';
  end if;

  if coalesce(v_aula.cancelada, false) then
    raise exception 'aula_cancelada';
  end if;

  if v_aula.data_hora_inicio > now() + interval '15 minutes' then
    raise exception 'chamada_ainda_nao_disponivel';
  end if;

  if coalesce(v_aula.data_hora_fim, v_aula.data_hora_inicio) < now() - interval '24 hours' then
    raise exception 'janela_de_chamada_encerrada';
  end if;

  select count(*), count(*) filter (where aluno_id is null)
  into v_roster_total, v_ja_existentes
  from public.aula_alunos_emusys
  where aula_emusys_id = v_aula.id;

  if v_roster_total = 0 then
    raise exception 'roster_nao_sincronizado';
  end if;

  if v_ja_existentes > 0 then
    raise exception 'roster_incompleto';
  end if;

  if exists (
    select 1
    from unnest(coalesce(p_alunos_ausentes, '{}'::integer[])) ausente(aluno_id)
    where not exists (
      select 1
      from public.aula_alunos_emusys r
      where r.aula_emusys_id = v_aula.id
        and r.aluno_id = ausente.aluno_id
    )
  ) then
    raise exception 'aluno_ausente_fora_do_roster';
  end if;

  select count(*) into v_ja_existentes
  from public.aluno_presenca ap
  where ap.aula_emusys_id = v_aula.id;

  if exists (
    select 1
    from public.aluno_presenca ap
    where ap.aula_emusys_id = v_aula.id
      and ap.respondido_por = 'professor_la_teacher'
  ) then
    return jsonb_build_object(
      'aula_id', v_aula.id,
      'total_roster', v_roster_total,
      'inseridos', 0,
      'ignorados_first_write_wins', v_roster_total,
      'ja_havia_registros', true,
      'chamada_ja_enviada', true
    );
  end if;

  insert into public.aluno_presenca (
    aluno_id,
    aula_emusys_id,
    professor_id,
    unidade_id,
    data_aula,
    horario_aula,
    status,
    status_presenca,
    curso_nome,
    turma_nome,
    sala_nome,
    respondido_por,
    respondido_em
  )
  select distinct
    r.aluno_id,
    v_aula.id,
    v_professor_id,
    v_aula.unidade_id,
    v_aula.data_aula,
    (v_aula.data_hora_inicio at time zone 'America/Sao_Paulo')::time,
    case when r.aluno_id = any(coalesce(p_alunos_ausentes, '{}'::integer[])) then 'ausente' else 'presente' end,
    case when r.aluno_id = any(coalesce(p_alunos_ausentes, '{}'::integer[])) then 'falta' else 'presente' end,
    v_aula.curso_nome,
    v_aula.turma_nome,
    v_aula.sala_nome,
    'professor_la_teacher',
    now()
  from public.aula_alunos_emusys r
  where r.aula_emusys_id = v_aula.id
    and r.aluno_id is not null
  on conflict (aluno_id, aula_emusys_id) do nothing;

  get diagnostics v_inseridos = row_count;

  return jsonb_build_object(
    'aula_id', v_aula.id,
    'total_roster', v_roster_total,
    'inseridos', v_inseridos,
    'ignorados_first_write_wins', v_roster_total - v_inseridos,
    'ja_havia_registros', v_ja_existentes > 0
  );
end;
$$;

revoke all on function public.app_registrar_presencas_aula(integer, integer[]) from public, anon;
grant execute on function public.app_registrar_presencas_aula(integer, integer[]) to authenticated;

create or replace function public.app_responder_confirmacao_ponto(
  p_aula_emusys_id integer,
  p_estava_presente boolean
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_professor_id integer := public.fn_professor_do_usuario();
  v_aula public.aulas_emusys%rowtype;
  v_inseridos integer;
begin
  if v_professor_id is null then
    raise exception 'sem_professor_vinculado' using errcode = '42501';
  end if;

  select * into v_aula
  from public.aulas_emusys
  where id = p_aula_emusys_id
    and professor_id = v_professor_id
    and cancelada = false;

  if not found then
    raise exception 'aula_nao_pertence_ao_professor' using errcode = '42501';
  end if;

  if v_aula.data_hora_inicio > now() then
    raise exception 'aula_ainda_nao_ocorreu';
  end if;

  insert into public.professor_ponto_confirmacoes (
    professor_id, aula_emusys_id, unidade_id, data_aula, estava_presente, origem
  ) values (
    v_professor_id, v_aula.id, v_aula.unidade_id, v_aula.data_aula, p_estava_presente, 'fabio'
  )
  on conflict (professor_id, aula_emusys_id) do nothing;

  get diagnostics v_inseridos = row_count;
  return jsonb_build_object('registrado', v_inseridos = 1, 'first_write_wins', v_inseridos = 0);
end;
$$;

revoke all on function public.app_responder_confirmacao_ponto(integer, boolean) from public, anon;
grant execute on function public.app_responder_confirmacao_ponto(integer, boolean) to authenticated;

create or replace function public.admin_corrigir_presenca(
  p_aluno_presenca_id uuid,
  p_status_presenca text,
  p_motivo text
)
returns public.aluno_presenca
language plpgsql
security definer
set search_path = public
as $$
declare
  v_usuario_id integer;
  v_registro public.aluno_presenca%rowtype;
  v_status_anterior text;
  v_resultado public.aluno_presenca%rowtype;
begin
  if p_status_presenca not in ('presente', 'falta') then
    raise exception 'status_presenca_invalido';
  end if;

  if length(btrim(coalesce(p_motivo, ''))) < 3 then
    raise exception 'motivo_obrigatorio';
  end if;

  select id into v_usuario_id
  from public.usuarios
  where auth_user_id = auth.uid()
    and coalesce(ativo, true)
  limit 1;

  select * into v_registro
  from public.aluno_presenca
  where id = p_aluno_presenca_id
  for update;

  if not found then
    raise exception 'presenca_nao_encontrada';
  end if;

  if v_usuario_id is null
     or not public.usuario_tem_permissao(v_usuario_id, 'professores.editar', v_registro.unidade_id) then
    raise exception 'sem_permissao_para_corrigir_presenca' using errcode = '42501';
  end if;

  v_status_anterior := coalesce(
    v_registro.status_presenca,
    case v_registro.status when 'presente' then 'presente' when 'ausente' then 'falta' end
  );

  insert into public.aluno_presenca_retificacoes (
    aluno_presenca_id,
    unidade_id,
    status_anterior,
    status_novo,
    respondido_por_anterior,
    respondido_em_anterior,
    motivo,
    autor_usuario_id,
    autor_auth_user_id
  ) values (
    v_registro.id,
    v_registro.unidade_id,
    v_status_anterior,
    p_status_presenca,
    v_registro.respondido_por,
    v_registro.respondido_em,
    btrim(p_motivo),
    v_usuario_id,
    auth.uid()
  );

  update public.aluno_presenca
  set
    status_presenca = p_status_presenca,
    status = case p_status_presenca when 'falta' then 'ausente' else 'presente' end,
    respondido_por = 'manual',
    respondido_em = now()
  where id = v_registro.id
  returning * into v_resultado;

  return v_resultado;
end;
$$;

revoke all on function public.admin_corrigir_presenca(uuid, text, text) from public, anon;
grant execute on function public.admin_corrigir_presenca(uuid, text, text) to authenticated;

create or replace view public.vw_ponto_professor_aulas
with (security_invoker = true)
as
with presenca_por_aula as (
  select
    ap.aula_emusys_id,
    bool_or(coalesce(ap.status_presenca, case ap.status when 'presente' then 'presente' when 'ausente' then 'falta' end) = 'presente') as tem_presenca,
    bool_or(coalesce(ap.status_presenca, case ap.status when 'presente' then 'presente' when 'ausente' then 'falta' end) = 'falta') as tem_falta
  from public.aluno_presenca ap
  where ap.aula_emusys_id is not null
  group by ap.aula_emusys_id
), aulas_base as (
  select
    ae.id as aula_emusys_id,
    ae.professor_id,
    ae.unidade_id,
    ae.data_aula,
    ae.data_hora_inicio,
    ae.data_hora_fim,
    greatest(
      1,
      coalesce(
        ae.duracao_minutos,
        round(extract(epoch from (ae.data_hora_fim - ae.data_hora_inicio)) / 60.0)::integer
      )
    ) as duracao_minutos,
    coalesce(pa.tem_presenca, false) as tem_presenca,
    coalesce(pa.tem_falta, false) as tem_falta,
    coalesce(pc.estava_presente, false) as ponta_confirmada,
    coalesce(pa.tem_presenca, false) or coalesce(pc.estava_presente, false) as evidencia_presenca
  from public.aulas_emusys ae
  left join presenca_por_aula pa on pa.aula_emusys_id = ae.id
  left join public.professor_ponto_confirmacoes pc
    on pc.aula_emusys_id = ae.id
   and pc.professor_id = ae.professor_id
  where ae.cancelada = false
    and ae.professor_id is not null
), ancoras as (
  select
    professor_id,
    data_aula,
    min(data_hora_inicio) filter (where evidencia_presenca) as primeira_evidencia_inicio,
    max(data_hora_inicio) filter (where evidencia_presenca) as ultima_evidencia_inicio
  from aulas_base
  group by professor_id, data_aula
)
select
  ab.*,
  an.primeira_evidencia_inicio,
  an.ultima_evidencia_inicio,
  an.primeira_evidencia_inicio is not null
    and ab.data_hora_inicio between an.primeira_evidencia_inicio and an.ultima_evidencia_inicio
    as aula_creditada
from aulas_base ab
join ancoras an using (professor_id, data_aula);

create or replace view public.vw_ponto_professor_diario
with (security_invoker = true)
as
select
  professor_id,
  data_aula,
  array_agg(distinct unidade_id order by unidade_id) filter (where aula_creditada) as unidades_ids,
  min(data_hora_inicio) filter (where aula_creditada) as inicio_creditado,
  max(data_hora_fim) filter (where aula_creditada) as fim_creditado,
  coalesce(sum(duracao_minutos) filter (where aula_creditada), 0)::integer as minutos_creditados,
  count(*) filter (where aula_creditada)::integer as aulas_creditadas,
  count(*) filter (where aula_creditada and ponta_confirmada)::integer as pontas_confirmadas
from public.vw_ponto_professor_aulas
group by professor_id, data_aula;

create or replace function public.app_meu_ponto(
  p_data_inicio date default current_date,
  p_data_fim date default current_date
)
returns table (
  data_aula date,
  unidades_ids uuid[],
  inicio_creditado timestamptz,
  fim_creditado timestamptz,
  minutos_creditados integer,
  aulas_creditadas integer,
  pontas_confirmadas integer
)
language sql
stable
security definer
set search_path = public
as $$
  select
    p.data_aula,
    p.unidades_ids,
    p.inicio_creditado,
    p.fim_creditado,
    p.minutos_creditados,
    p.aulas_creditadas,
    p.pontas_confirmadas
  from public.vw_ponto_professor_diario p
  where p.professor_id = public.fn_professor_do_usuario()
    and p.data_aula between p_data_inicio and p_data_fim
  order by p.data_aula;
$$;

revoke all on function public.app_meu_ponto(date, date) from public, anon;
grant execute on function public.app_meu_ponto(date, date) to authenticated;

revoke all on table public.vw_ponto_professor_aulas from anon, authenticated;
revoke all on table public.vw_ponto_professor_diario from anon, authenticated;

comment on table public.aula_alunos_emusys is
  'Roster operacional de aulas do Emusys, sem contato ou dados financeiros.';
comment on table public.aluno_presenca_administrativo is
  'Camada administrativa read-only para o professor; justificada vem do Emusys.';
comment on table public.aluno_presenca_retificacoes is
  'Trilha append-only de correcoes de presenca feitas pela coordenacao.';
comment on view public.vw_ponto_professor_diario is
  'Ponto derivado pela soma das aulas distintas entre a primeira e a ultima evidencia de presenca.';
