-- [RECUPERADA DO HISTORICO 2026-08-22, issue #201] Migration aplicada em producao
-- (via CLI/MCP) sem arquivo versionado. SQL extraido de supabase_migrations.
-- schema_migrations (statements como aplicados). NAO REAPLICAR: ja esta no
-- schema_migrations com esta mesma version.


DROP POLICY IF EXISTS "aluno_contatos_delete" ON public.aluno_contatos;
CREATE POLICY "aluno_contatos_delete" ON public.aluno_contatos FOR DELETE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "aluno_contatos_insert" ON public.aluno_contatos;
CREATE POLICY "aluno_contatos_insert" ON public.aluno_contatos FOR INSERT TO authenticated, sol_acesso_restrito, mila_acesso_restrito WITH CHECK (true);
DROP POLICY IF EXISTS "aluno_contatos_select" ON public.aluno_contatos;
CREATE POLICY "aluno_contatos_select" ON public.aluno_contatos FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "aluno_contatos_update" ON public.aluno_contatos;
CREATE POLICY "aluno_contatos_update" ON public.aluno_contatos FOR UPDATE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "health_score_historico_all" ON public.alunos_health_score_historico;
CREATE POLICY "health_score_historico_all" ON public.alunos_health_score_historico FOR ALL TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "alunos_historico_delete" ON public.alunos_historico;
CREATE POLICY "alunos_historico_delete" ON public.alunos_historico FOR DELETE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "alunos_historico_insert" ON public.alunos_historico;
CREATE POLICY "alunos_historico_insert" ON public.alunos_historico FOR INSERT TO authenticated, sol_acesso_restrito, mila_acesso_restrito WITH CHECK (true);
DROP POLICY IF EXISTS "alunos_historico_select" ON public.alunos_historico;
CREATE POLICY "alunos_historico_select" ON public.alunos_historico FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "alunos_historico_update" ON public.alunos_historico;
CREATE POLICY "alunos_historico_update" ON public.alunos_historico FOR UPDATE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "Permitir escrita publica anotacoes" ON public.anotacoes;
CREATE POLICY "Permitir escrita publica anotacoes" ON public.anotacoes FOR ALL TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Permitir leitura publica anotacoes" ON public.anotacoes;
CREATE POLICY "Permitir leitura publica anotacoes" ON public.anotacoes FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "Permitir insercao publica audit_log" ON public.audit_log;
CREATE POLICY "Permitir insercao publica audit_log" ON public.audit_log FOR INSERT TO authenticated, sol_acesso_restrito, mila_acesso_restrito WITH CHECK (true);
DROP POLICY IF EXISTS "Permitir leitura publica audit_log" ON public.audit_log;
CREATE POLICY "Permitir leitura publica audit_log" ON public.audit_log FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "Auditoria: sistema pode inserir" ON public.auditoria_acesso;
CREATE POLICY "Auditoria: sistema pode inserir" ON public.auditoria_acesso FOR INSERT TO authenticated, sol_acesso_restrito, mila_acesso_restrito WITH CHECK (true);
DROP POLICY IF EXISTS "Allow insert for all" ON public.automacao_log;
CREATE POLICY "Allow insert for all" ON public.automacao_log FOR INSERT TO authenticated, sol_acesso_restrito, mila_acesso_restrito WITH CHECK (true);
DROP POLICY IF EXISTS "bi_msg_insert" ON public.bi_messages_lamusic;
CREATE POLICY "bi_msg_insert" ON public.bi_messages_lamusic FOR INSERT TO authenticated, sol_acesso_restrito, mila_acesso_restrito WITH CHECK (true);
DROP POLICY IF EXISTS "bi_msg_select" ON public.bi_messages_lamusic;
CREATE POLICY "bi_msg_select" ON public.bi_messages_lamusic FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "bi_msg_update" ON public.bi_messages_lamusic;
CREATE POLICY "bi_msg_update" ON public.bi_messages_lamusic FOR UPDATE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "bi_cache_all" ON public.bi_query_cache_lamusic;
CREATE POLICY "bi_cache_all" ON public.bi_query_cache_lamusic FOR ALL TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "campanhas_delete" ON public.campanhas;
CREATE POLICY "campanhas_delete" ON public.campanhas FOR DELETE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "canais_origem_insert" ON public.canais_origem;
CREATE POLICY "canais_origem_insert" ON public.canais_origem FOR INSERT TO authenticated, sol_acesso_restrito, mila_acesso_restrito WITH CHECK (true);
DROP POLICY IF EXISTS "canais_origem_select_policy" ON public.canais_origem;
CREATE POLICY "canais_origem_select_policy" ON public.canais_origem FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "crm_conversas_delete" ON public.crm_conversas;
CREATE POLICY "crm_conversas_delete" ON public.crm_conversas FOR DELETE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "crm_conversas_insert" ON public.crm_conversas;
CREATE POLICY "crm_conversas_insert" ON public.crm_conversas FOR INSERT TO authenticated, sol_acesso_restrito, mila_acesso_restrito WITH CHECK (true);
DROP POLICY IF EXISTS "crm_conversas_select" ON public.crm_conversas;
CREATE POLICY "crm_conversas_select" ON public.crm_conversas FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "crm_conversas_update" ON public.crm_conversas;
CREATE POLICY "crm_conversas_update" ON public.crm_conversas FOR UPDATE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "crm_etiquetas_all" ON public.crm_etiquetas;
CREATE POLICY "crm_etiquetas_all" ON public.crm_etiquetas FOR ALL TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "crm_etiquetas_select" ON public.crm_etiquetas;
CREATE POLICY "crm_etiquetas_select" ON public.crm_etiquetas FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "crm_lead_etiquetas_all" ON public.crm_lead_etiquetas;
CREATE POLICY "crm_lead_etiquetas_all" ON public.crm_lead_etiquetas FOR ALL TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "crm_lead_etiquetas_select" ON public.crm_lead_etiquetas;
CREATE POLICY "crm_lead_etiquetas_select" ON public.crm_lead_etiquetas FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "crm_mensagens_delete" ON public.crm_mensagens;
CREATE POLICY "crm_mensagens_delete" ON public.crm_mensagens FOR DELETE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "crm_mensagens_insert" ON public.crm_mensagens;
CREATE POLICY "crm_mensagens_insert" ON public.crm_mensagens FOR INSERT TO authenticated, sol_acesso_restrito, mila_acesso_restrito WITH CHECK (true);
DROP POLICY IF EXISTS "crm_mensagens_select" ON public.crm_mensagens;
CREATE POLICY "crm_mensagens_select" ON public.crm_mensagens FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "crm_mensagens_update" ON public.crm_mensagens;
CREATE POLICY "crm_mensagens_update" ON public.crm_mensagens FOR UPDATE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "cursos_matriculados_delete" ON public.cursos_matriculados;
CREATE POLICY "cursos_matriculados_delete" ON public.cursos_matriculados FOR DELETE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "cursos_matriculados_insert" ON public.cursos_matriculados;
CREATE POLICY "cursos_matriculados_insert" ON public.cursos_matriculados FOR INSERT TO authenticated, sol_acesso_restrito, mila_acesso_restrito WITH CHECK (true);
DROP POLICY IF EXISTS "cursos_matriculados_select" ON public.cursos_matriculados;
CREATE POLICY "cursos_matriculados_select" ON public.cursos_matriculados FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "cursos_matriculados_update" ON public.cursos_matriculados;
CREATE POLICY "cursos_matriculados_update" ON public.cursos_matriculados FOR UPDATE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "dados_comerciais_delete" ON public.dados_comerciais_legado;
CREATE POLICY "dados_comerciais_delete" ON public.dados_comerciais_legado FOR DELETE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "dados_comerciais_insert" ON public.dados_comerciais_legado;
CREATE POLICY "dados_comerciais_insert" ON public.dados_comerciais_legado FOR INSERT TO authenticated, sol_acesso_restrito, mila_acesso_restrito WITH CHECK (true);
DROP POLICY IF EXISTS "dados_comerciais_select" ON public.dados_comerciais_legado;
CREATE POLICY "dados_comerciais_select" ON public.dados_comerciais_legado FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "dados_comerciais_update" ON public.dados_comerciais_legado;
CREATE POLICY "dados_comerciais_update" ON public.dados_comerciais_legado FOR UPDATE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "Permitir escrita publica dados_mensais" ON public.dados_mensais;
CREATE POLICY "Permitir escrita publica dados_mensais" ON public.dados_mensais FOR ALL TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Permitir leitura publica dados_mensais" ON public.dados_mensais;
CREATE POLICY "Permitir leitura publica dados_mensais" ON public.dados_mensais FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "Permitir escrita publica dashboard_config" ON public.dashboard_config;
CREATE POLICY "Permitir escrita publica dashboard_config" ON public.dashboard_config FOR ALL TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Permitir leitura publica dashboard_config" ON public.dashboard_config;
CREATE POLICY "Permitir leitura publica dashboard_config" ON public.dashboard_config FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "experimentais_mensal_unidade_delete" ON public.experimentais_mensal_unidade;
CREATE POLICY "experimentais_mensal_unidade_delete" ON public.experimentais_mensal_unidade FOR DELETE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "experimentais_mensal_unidade_insert" ON public.experimentais_mensal_unidade;
CREATE POLICY "experimentais_mensal_unidade_insert" ON public.experimentais_mensal_unidade FOR INSERT TO authenticated, sol_acesso_restrito, mila_acesso_restrito WITH CHECK (true);
DROP POLICY IF EXISTS "experimentais_mensal_unidade_select" ON public.experimentais_mensal_unidade;
CREATE POLICY "experimentais_mensal_unidade_select" ON public.experimentais_mensal_unidade FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "experimentais_mensal_unidade_update" ON public.experimentais_mensal_unidade;
CREATE POLICY "experimentais_mensal_unidade_update" ON public.experimentais_mensal_unidade FOR UPDATE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "experimentais_professor_mensal_delete" ON public.experimentais_professor_mensal;
CREATE POLICY "experimentais_professor_mensal_delete" ON public.experimentais_professor_mensal FOR DELETE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "experimentais_professor_mensal_insert" ON public.experimentais_professor_mensal;
CREATE POLICY "experimentais_professor_mensal_insert" ON public.experimentais_professor_mensal FOR INSERT TO authenticated, sol_acesso_restrito, mila_acesso_restrito WITH CHECK (true);
DROP POLICY IF EXISTS "experimentais_professor_mensal_select" ON public.experimentais_professor_mensal;
CREATE POLICY "experimentais_professor_mensal_select" ON public.experimentais_professor_mensal FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "experimentais_professor_mensal_update" ON public.experimentais_professor_mensal;
CREATE POLICY "experimentais_professor_mensal_update" ON public.experimentais_professor_mensal FOR UPDATE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "farmer_checklist_contatos_delete" ON public.farmer_checklist_contatos;
CREATE POLICY "farmer_checklist_contatos_delete" ON public.farmer_checklist_contatos FOR DELETE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "farmer_checklist_contatos_insert" ON public.farmer_checklist_contatos;
CREATE POLICY "farmer_checklist_contatos_insert" ON public.farmer_checklist_contatos FOR INSERT TO authenticated, sol_acesso_restrito, mila_acesso_restrito WITH CHECK (true);
DROP POLICY IF EXISTS "farmer_checklist_contatos_select" ON public.farmer_checklist_contatos;
CREATE POLICY "farmer_checklist_contatos_select" ON public.farmer_checklist_contatos FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "farmer_checklist_contatos_update" ON public.farmer_checklist_contatos;
CREATE POLICY "farmer_checklist_contatos_update" ON public.farmer_checklist_contatos FOR UPDATE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "farmer_checklist_items_delete" ON public.farmer_checklist_items;
CREATE POLICY "farmer_checklist_items_delete" ON public.farmer_checklist_items FOR DELETE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "farmer_checklist_items_insert" ON public.farmer_checklist_items;
CREATE POLICY "farmer_checklist_items_insert" ON public.farmer_checklist_items FOR INSERT TO authenticated, sol_acesso_restrito, mila_acesso_restrito WITH CHECK (true);
DROP POLICY IF EXISTS "farmer_checklist_items_select" ON public.farmer_checklist_items;
CREATE POLICY "farmer_checklist_items_select" ON public.farmer_checklist_items FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "farmer_checklist_items_update" ON public.farmer_checklist_items;
CREATE POLICY "farmer_checklist_items_update" ON public.farmer_checklist_items FOR UPDATE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "farmer_checklist_templates_insert" ON public.farmer_checklist_templates;
CREATE POLICY "farmer_checklist_templates_insert" ON public.farmer_checklist_templates FOR INSERT TO authenticated, sol_acesso_restrito, mila_acesso_restrito WITH CHECK (true);
DROP POLICY IF EXISTS "farmer_checklist_templates_select" ON public.farmer_checklist_templates;
CREATE POLICY "farmer_checklist_templates_select" ON public.farmer_checklist_templates FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "farmer_checklist_templates_update" ON public.farmer_checklist_templates;
CREATE POLICY "farmer_checklist_templates_update" ON public.farmer_checklist_templates FOR UPDATE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "farmer_checklists_delete" ON public.farmer_checklists;
CREATE POLICY "farmer_checklists_delete" ON public.farmer_checklists FOR DELETE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "farmer_checklists_insert" ON public.farmer_checklists;
CREATE POLICY "farmer_checklists_insert" ON public.farmer_checklists FOR INSERT TO authenticated, sol_acesso_restrito, mila_acesso_restrito WITH CHECK (true);
DROP POLICY IF EXISTS "farmer_checklists_select" ON public.farmer_checklists;
CREATE POLICY "farmer_checklists_select" ON public.farmer_checklists FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "farmer_checklists_update" ON public.farmer_checklists;
CREATE POLICY "farmer_checklists_update" ON public.farmer_checklists FOR UPDATE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "recados_campanhas_all" ON public.farmer_recados_campanhas;
CREATE POLICY "recados_campanhas_all" ON public.farmer_recados_campanhas FOR ALL TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "recados_destinatarios_all" ON public.farmer_recados_destinatarios;
CREATE POLICY "recados_destinatarios_all" ON public.farmer_recados_destinatarios FOR ALL TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "horarios_insert" ON public.horarios;
CREATE POLICY "horarios_insert" ON public.horarios FOR INSERT TO authenticated, sol_acesso_restrito, mila_acesso_restrito WITH CHECK (true);
DROP POLICY IF EXISTS "metas_comerciais_delete" ON public.metas_comerciais;
CREATE POLICY "metas_comerciais_delete" ON public.metas_comerciais FOR DELETE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "metas_comerciais_insert" ON public.metas_comerciais;
CREATE POLICY "metas_comerciais_insert" ON public.metas_comerciais FOR INSERT TO authenticated, sol_acesso_restrito, mila_acesso_restrito WITH CHECK (true);
DROP POLICY IF EXISTS "metas_comerciais_select" ON public.metas_comerciais;
CREATE POLICY "metas_comerciais_select" ON public.metas_comerciais FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "metas_comerciais_update" ON public.metas_comerciais;
CREATE POLICY "metas_comerciais_update" ON public.metas_comerciais FOR UPDATE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "Permitir escrita publica metas" ON public.metas_legado;
CREATE POLICY "Permitir escrita publica metas" ON public.metas_legado FOR ALL TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Permitir leitura publica metas" ON public.metas_legado;
CREATE POLICY "Permitir leitura publica metas" ON public.metas_legado FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "Permitir acesso total para usuários autenticados" ON public.metas_professor_turma;
CREATE POLICY "Permitir acesso total para usuários autenticados" ON public.metas_professor_turma FOR ALL TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "motivos_arquivamento_delete" ON public.motivos_arquivamento;
CREATE POLICY "motivos_arquivamento_delete" ON public.motivos_arquivamento FOR DELETE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "motivos_arquivamento_insert" ON public.motivos_arquivamento;
CREATE POLICY "motivos_arquivamento_insert" ON public.motivos_arquivamento FOR INSERT TO authenticated, sol_acesso_restrito, mila_acesso_restrito WITH CHECK (true);
DROP POLICY IF EXISTS "motivos_arquivamento_update" ON public.motivos_arquivamento;
CREATE POLICY "motivos_arquivamento_update" ON public.motivos_arquivamento FOR UPDATE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "motivos_nao_matricula_delete" ON public.motivos_nao_matricula;
CREATE POLICY "motivos_nao_matricula_delete" ON public.motivos_nao_matricula FOR DELETE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "motivos_nao_matricula_insert" ON public.motivos_nao_matricula;
CREATE POLICY "motivos_nao_matricula_insert" ON public.motivos_nao_matricula FOR INSERT TO authenticated, sol_acesso_restrito, mila_acesso_restrito WITH CHECK (true);
DROP POLICY IF EXISTS "motivos_nao_matricula_select" ON public.motivos_nao_matricula;
CREATE POLICY "motivos_nao_matricula_select" ON public.motivos_nao_matricula FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "motivos_nao_matricula_update" ON public.motivos_nao_matricula;
CREATE POLICY "motivos_nao_matricula_update" ON public.motivos_nao_matricula FOR UPDATE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "motivos_saida_delete" ON public.motivos_saida;
CREATE POLICY "motivos_saida_delete" ON public.motivos_saida FOR DELETE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "motivos_saida_insert" ON public.motivos_saida;
CREATE POLICY "motivos_saida_insert" ON public.motivos_saida FOR INSERT TO authenticated, sol_acesso_restrito, mila_acesso_restrito WITH CHECK (true);
DROP POLICY IF EXISTS "motivos_saida_select" ON public.motivos_saida;
CREATE POLICY "motivos_saida_select" ON public.motivos_saida FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "motivos_saida_update" ON public.motivos_saida;
CREATE POLICY "motivos_saida_update" ON public.motivos_saida FOR UPDATE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "motivos_trancamento_delete" ON public.motivos_trancamento;
CREATE POLICY "motivos_trancamento_delete" ON public.motivos_trancamento FOR DELETE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "motivos_trancamento_insert" ON public.motivos_trancamento;
CREATE POLICY "motivos_trancamento_insert" ON public.motivos_trancamento FOR INSERT TO authenticated, sol_acesso_restrito, mila_acesso_restrito WITH CHECK (true);
DROP POLICY IF EXISTS "motivos_trancamento_update" ON public.motivos_trancamento;
CREATE POLICY "motivos_trancamento_update" ON public.motivos_trancamento FOR UPDATE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "origem_leads_delete" ON public.origem_leads_legado;
CREATE POLICY "origem_leads_delete" ON public.origem_leads_legado FOR DELETE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "origem_leads_insert" ON public.origem_leads_legado;
CREATE POLICY "origem_leads_insert" ON public.origem_leads_legado FOR INSERT TO authenticated, sol_acesso_restrito, mila_acesso_restrito WITH CHECK (true);
DROP POLICY IF EXISTS "origem_leads_select" ON public.origem_leads_legado;
CREATE POLICY "origem_leads_select" ON public.origem_leads_legado FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "origem_leads_update" ON public.origem_leads_legado;
CREATE POLICY "origem_leads_update" ON public.origem_leads_legado FOR UPDATE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "Perfil_permissoes: leitura pública" ON public.perfil_permissoes;
CREATE POLICY "Perfil_permissoes: leitura pública" ON public.perfil_permissoes FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "Perfis: leitura pública" ON public.perfis;
CREATE POLICY "Perfis: leitura pública" ON public.perfis FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "Permissoes: leitura pública" ON public.permissoes;
CREATE POLICY "Permissoes: leitura pública" ON public.permissoes FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "pesquisa_evasao_all" ON public.pesquisa_evasao;
CREATE POLICY "pesquisa_evasao_all" ON public.pesquisa_evasao FOR ALL TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "planos_acao_delete" ON public.planos_acao;
CREATE POLICY "planos_acao_delete" ON public.planos_acao FOR DELETE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "planos_acao_insert" ON public.planos_acao;
CREATE POLICY "planos_acao_insert" ON public.planos_acao FOR INSERT TO authenticated, sol_acesso_restrito, mila_acesso_restrito WITH CHECK (true);
DROP POLICY IF EXISTS "planos_acao_select" ON public.planos_acao;
CREATE POLICY "planos_acao_select" ON public.planos_acao FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "planos_acao_update" ON public.planos_acao;
CREATE POLICY "planos_acao_update" ON public.planos_acao FOR UPDATE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "select_professor_360_ocorrencias_log" ON public.professor_360_ocorrencias_log;
CREATE POLICY "select_professor_360_ocorrencias_log" ON public.professor_360_ocorrencias_log FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "professor_videos_select" ON public.professor_videos;
CREATE POLICY "professor_videos_select" ON public.professor_videos FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "professores_experimentais_delete" ON public.professores_experimentais;
CREATE POLICY "professores_experimentais_delete" ON public.professores_experimentais FOR DELETE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "professores_experimentais_insert" ON public.professores_experimentais;
CREATE POLICY "professores_experimentais_insert" ON public.professores_experimentais FOR INSERT TO authenticated, sol_acesso_restrito, mila_acesso_restrito WITH CHECK (true);
DROP POLICY IF EXISTS "professores_experimentais_select" ON public.professores_experimentais;
CREATE POLICY "professores_experimentais_select" ON public.professores_experimentais FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "professores_experimentais_update" ON public.professores_experimentais;
CREATE POLICY "professores_experimentais_update" ON public.professores_experimentais FOR UPDATE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "professores_performance_delete" ON public.professores_performance;
CREATE POLICY "professores_performance_delete" ON public.professores_performance FOR DELETE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "professores_performance_insert" ON public.professores_performance;
CREATE POLICY "professores_performance_insert" ON public.professores_performance FOR INSERT TO authenticated, sol_acesso_restrito, mila_acesso_restrito WITH CHECK (true);
DROP POLICY IF EXISTS "professores_performance_select" ON public.professores_performance;
CREATE POLICY "professores_performance_select" ON public.professores_performance FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "professores_performance_update" ON public.professores_performance;
CREATE POLICY "professores_performance_update" ON public.professores_performance FOR UPDATE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "select_programa_fideliza_config" ON public.programa_fideliza_config;
CREATE POLICY "select_programa_fideliza_config" ON public.programa_fideliza_config FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "select_programa_fideliza_experiencias" ON public.programa_fideliza_experiencias;
CREATE POLICY "select_programa_fideliza_experiencias" ON public.programa_fideliza_experiencias FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "select_programa_fideliza_historico" ON public.programa_fideliza_historico;
CREATE POLICY "select_programa_fideliza_historico" ON public.programa_fideliza_historico FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "select_programa_fideliza_penalidades" ON public.programa_fideliza_penalidades;
CREATE POLICY "select_programa_fideliza_penalidades" ON public.programa_fideliza_penalidades FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "projeto_equipe_delete_policy" ON public.projeto_equipe;
CREATE POLICY "projeto_equipe_delete_policy" ON public.projeto_equipe FOR DELETE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "projeto_equipe_insert_policy" ON public.projeto_equipe;
CREATE POLICY "projeto_equipe_insert_policy" ON public.projeto_equipe FOR INSERT TO authenticated, sol_acesso_restrito, mila_acesso_restrito WITH CHECK (true);
DROP POLICY IF EXISTS "projeto_equipe_select_policy" ON public.projeto_equipe;
CREATE POLICY "projeto_equipe_select_policy" ON public.projeto_equipe FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "projeto_equipe_update_policy" ON public.projeto_equipe;
CREATE POLICY "projeto_equipe_update_policy" ON public.projeto_equipe FOR UPDATE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "projeto_fases_delete_policy" ON public.projeto_fases;
CREATE POLICY "projeto_fases_delete_policy" ON public.projeto_fases FOR DELETE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "projeto_fases_insert_policy" ON public.projeto_fases;
CREATE POLICY "projeto_fases_insert_policy" ON public.projeto_fases FOR INSERT TO authenticated, sol_acesso_restrito, mila_acesso_restrito WITH CHECK (true);
DROP POLICY IF EXISTS "projeto_fases_select_policy" ON public.projeto_fases;
CREATE POLICY "projeto_fases_select_policy" ON public.projeto_fases FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "projeto_fases_update_policy" ON public.projeto_fases;
CREATE POLICY "projeto_fases_update_policy" ON public.projeto_fases FOR UPDATE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "projeto_tarefas_delete_policy" ON public.projeto_tarefas;
CREATE POLICY "projeto_tarefas_delete_policy" ON public.projeto_tarefas FOR DELETE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "projeto_tarefas_insert_policy" ON public.projeto_tarefas;
CREATE POLICY "projeto_tarefas_insert_policy" ON public.projeto_tarefas FOR INSERT TO authenticated, sol_acesso_restrito, mila_acesso_restrito WITH CHECK (true);
DROP POLICY IF EXISTS "projeto_tarefas_select_policy" ON public.projeto_tarefas;
CREATE POLICY "projeto_tarefas_select_policy" ON public.projeto_tarefas FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "projeto_tarefas_update_policy" ON public.projeto_tarefas;
CREATE POLICY "projeto_tarefas_update_policy" ON public.projeto_tarefas FOR UPDATE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "projeto_tipo_fases_template_delete_policy" ON public.projeto_tipo_fases_template;
CREATE POLICY "projeto_tipo_fases_template_delete_policy" ON public.projeto_tipo_fases_template FOR DELETE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "projeto_tipo_fases_template_insert_policy" ON public.projeto_tipo_fases_template;
CREATE POLICY "projeto_tipo_fases_template_insert_policy" ON public.projeto_tipo_fases_template FOR INSERT TO authenticated, sol_acesso_restrito, mila_acesso_restrito WITH CHECK (true);
DROP POLICY IF EXISTS "projeto_tipo_fases_template_select_policy" ON public.projeto_tipo_fases_template;
CREATE POLICY "projeto_tipo_fases_template_select_policy" ON public.projeto_tipo_fases_template FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "projeto_tipo_fases_template_update_policy" ON public.projeto_tipo_fases_template;
CREATE POLICY "projeto_tipo_fases_template_update_policy" ON public.projeto_tipo_fases_template FOR UPDATE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "projeto_tipo_tarefas_template_delete_policy" ON public.projeto_tipo_tarefas_template;
CREATE POLICY "projeto_tipo_tarefas_template_delete_policy" ON public.projeto_tipo_tarefas_template FOR DELETE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "projeto_tipo_tarefas_template_insert_policy" ON public.projeto_tipo_tarefas_template;
CREATE POLICY "projeto_tipo_tarefas_template_insert_policy" ON public.projeto_tipo_tarefas_template FOR INSERT TO authenticated, sol_acesso_restrito, mila_acesso_restrito WITH CHECK (true);
DROP POLICY IF EXISTS "projeto_tipo_tarefas_template_select_policy" ON public.projeto_tipo_tarefas_template;
CREATE POLICY "projeto_tipo_tarefas_template_select_policy" ON public.projeto_tipo_tarefas_template FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "projeto_tipo_tarefas_template_update_policy" ON public.projeto_tipo_tarefas_template;
CREATE POLICY "projeto_tipo_tarefas_template_update_policy" ON public.projeto_tipo_tarefas_template FOR UPDATE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "projeto_tipos_delete_policy" ON public.projeto_tipos;
CREATE POLICY "projeto_tipos_delete_policy" ON public.projeto_tipos FOR DELETE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "projeto_tipos_insert_policy" ON public.projeto_tipos;
CREATE POLICY "projeto_tipos_insert_policy" ON public.projeto_tipos FOR INSERT TO authenticated, sol_acesso_restrito, mila_acesso_restrito WITH CHECK (true);
DROP POLICY IF EXISTS "projeto_tipos_select_policy" ON public.projeto_tipos;
CREATE POLICY "projeto_tipos_select_policy" ON public.projeto_tipos FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "projeto_tipos_update_policy" ON public.projeto_tipos;
CREATE POLICY "projeto_tipos_update_policy" ON public.projeto_tipos FOR UPDATE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "projetos_delete_policy" ON public.projetos;
CREATE POLICY "projetos_delete_policy" ON public.projetos FOR DELETE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "projetos_insert_policy" ON public.projetos;
CREATE POLICY "projetos_insert_policy" ON public.projetos FOR INSERT TO authenticated, sol_acesso_restrito, mila_acesso_restrito WITH CHECK (true);
DROP POLICY IF EXISTS "projetos_select_policy" ON public.projetos;
CREATE POLICY "projetos_select_policy" ON public.projetos FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "projetos_update_policy" ON public.projetos;
CREATE POLICY "projetos_update_policy" ON public.projetos FOR UPDATE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "Permitir acesso total para usuários autenticados" ON public.simulacoes_turma;
CREATE POLICY "Permitir acesso total para usuários autenticados" ON public.simulacoes_turma FOR ALL TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "templates_cenario_delete_policy" ON public.templates_cenario;
CREATE POLICY "templates_cenario_delete_policy" ON public.templates_cenario FOR DELETE TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
DROP POLICY IF EXISTS "tipos_saida_insert" ON public.tipos_saida;
CREATE POLICY "tipos_saida_insert" ON public.tipos_saida FOR INSERT TO authenticated, sol_acesso_restrito, mila_acesso_restrito WITH CHECK (true);
DROP POLICY IF EXISTS "tipos_saida_select" ON public.tipos_saida;
CREATE POLICY "tipos_saida_select" ON public.tipos_saida FOR SELECT TO authenticated, sol_acesso_restrito, mila_acesso_restrito USING (true);
