-- 2o ANDAR da vertical COMERCIAL — estrategias, cada uma com a VIABILIDADE
-- declarada. A pergunta "tenho capacidade para atender?" vem ANTES de propor.
--
-- ⚠️ EC2 (Instagram) fica com viabilidade DESCONHECIDA de proposito: a escola faz
-- 250 experimentais/mes hoje e a estrategia acrescentaria ~160. Nao sei se ha
-- sala, professor e horario. Prometer volume sem checar a agenda produz lead
-- marcado que nao e atendido — pior que lead nao trabalhado.
-- ⚠️ EC3 (ex-alunos) tem VIES DECLARADO: os 68,2% sao de quem voltou por conta
-- propria, ja decidido. Prospeccao fria nao tera essa taxa.
insert into public.radar_estrategias
  (codigo, titulo, descricao, tipo, responsavel_papel, capacidade_conhecida, capacidade_total, capacidade_usada, demanda_estimada, viabilidade, custo_relativo, evidencia_eficacia, ativo, observacao_operacional)
values
('EC1', 'Ligar para quem fez a experimental e não fechou', 'Todo lead que realizou a aula e ficou mais de 3 dias sem desfecho vira ligação da consultora no mesmo dia. Não mensagem: ligação.', 'comercial', 'consultora', true, null, null, 179, 'disponivel', 'baixo', 'PC1: quem faz a aula converte a 40-50% em TODOS os canais. Estes 179 já fizeram a aula — são a parte mais barata do funil, porque o custo de trazê-los até aqui já foi pago. 179 divididos por 3 unidades = ~60 por consultora, drenável em 2-3 semanas com teto de 8/dia.', true, 'Começar por aqui. É a única estratégia da lista cuja demanda cabe na capacidade atual sem nenhuma mudança de processo.'),
('EC2', 'Aumentar a taxa de agendamento do Instagram', 'Atacar o trecho entre o lead chegar pelo Instagram e ele marcar a aula — hoje 9 de cada 10 somem nesse trecho.', 'comercial', 'consultora', false, null, 250, 2998, 'desconhecida', 'alto', 'PC2: o Instagram traz 63% do volume e perde 90% antes da aula. Cada ponto percentual de agendamento a mais vale ~30 experimentais/mês.', true, '⚠️ VIABILIDADE NÃO CONFIRMADA: a escola faz 250 experimentais/mês hoje (média de 147 no semestre, ou seja, já vem subindo). Levar o Instagram de 9,6% para 15% acrescentaria ~160 por mês — 410 no total. NÃO SEI se há sala, professor e horário para isso, e prometer volume sem checar a agenda produz lead marcado que não é atendido, que é pior que lead não trabalhado. Medir a capacidade de slots ANTES de acionar.'),
('EC3', 'Prospectar ex-alunos', 'Trabalhar ativamente a base de quem já estudou na escola, começando por quem saiu por motivo reversível.', 'comercial', 'consultora', true, 288, 28, 288, 'limitada', 'medio', 'PC3: ex-aluno converte 68,2% de quem faz a aula — a maior taxa de todas — e o volume é de apenas 28 leads em 166 dias. Há 541 ex-alunos, 288 com telefone.', true, '⚠️ VIÉS DECLARADO: os 68,2% são de ex-alunos que voltaram POR CONTA PRÓPRIA — gente que já tinha decidido voltar. Prospecção fria não terá essa taxa, e usá-la para projetar resultado seria enganoso. O valor real depende da fatia `historico` do radar: saber POR QUE cada um saiu muda a abordagem, e sem isso é lista fria. Fazer depois que o histórico tiver motivo de saída.'),
('EC4', 'Descobrir o que há com o canal Site', 'Investigar por que 86 leads do site geraram zero matrículas: formulário quebrado, lead não trabalhado, ou origem gravada errada.', 'operacional', 'gestao', true, null, null, 86, 'disponivel', 'baixo', 'PC4: 86 leads, 1 agendou, ZERO converteram. Não é taxa baixa, é ausência total — o que aponta para defeito, não para mercado.', true, 'Custa uma tarde. Três hipóteses na ordem: (1) submeter o formulário do site e ver se o lead chega; (2) conferir se alguém abre esses leads; (3) checar se a origem "Site" não está sendo usada como default de importação.')
on conflict (codigo) do update
  set titulo=excluded.titulo, descricao=excluded.descricao, tipo=excluded.tipo, responsavel_papel=excluded.responsavel_papel, capacidade_conhecida=excluded.capacidade_conhecida, capacidade_total=excluded.capacidade_total, capacidade_usada=excluded.capacidade_usada, demanda_estimada=excluded.demanda_estimada, viabilidade=excluded.viabilidade, custo_relativo=excluded.custo_relativo, evidencia_eficacia=excluded.evidencia_eficacia, observacao_operacional=excluded.observacao_operacional, atualizada_em=now();
